### ISSUE TITLE
SDWebImageRefreshCached Not Working

### ISSUE THREAD

**Issue by mohamedadly** [rs/SDWebImage#1029]
I use this url to get the user's Facebook profile image.

https://graph.facebook.com/100007160439164/picture?width=200&height=200

if the user changed his image on Facebook, it doesn't refresh in the app. even if using the SDWebImageRefreshCached option.

**Comment by mythodeia** [comment]
@mohamedadly can you try this https://github.com/rs/SDWebImage/issues/951#issuecomment-62358369 and let me know if it works for you

**Comment by mohamedadly** [comment]
@mythodeia  actually it is better than before, but still sometimes it returns the cached image.

**Comment by mythodeia** [comment]
thats weird since with the mentioned code in the comment the image is loaded again from the online url and not from disk / cache. 
if you load the url to a browser you will see that the image is retrieved from akamai cdn
```https://fbcdn-profile-a.akamaihd.net/```
is there a chance the image is not yet loaded to the akamai cdn and thats why it sometimes works and sometimes it does not? maybe the akamai server does not have the new image yet.

**Comment by mohamedadly** [comment]
yes, maybe the problem is from the CDN.
I noticed many times that even on web browser it takes a long delay till the image is refreshed.
but i noticed a strange behaviour, if i use the username instead of the numeric user id, the image is refreshed much faster.

i don't know honestly if there is something wrong with Facebook's CDN.

**Comment by mythodeia** [comment]
it does not mean its something wrong. it just takes time to sent the new image to the cdn and then cache it and sent it to all server instances. Since as you said it sometimes takes time to refresh the image to the browser as well then the "issue" is with the cdn's response time.

If like you said using the username instead of the numeric user id makes the image refresh faster then continue using that :)

**Comment by mohamedadly** [comment]
Yeah i will use that, but the problem that not all Facebook users have usernames.

anyway, i hope to include this fix in the pod version as well.

**Comment by bpoplauschi** [comment]
@mythodeia is there anything else we can do here?

**Comment by mythodeia** [comment]
i don't see anything else we can do here. closing this

**Comment by bpoplauschi** [comment]
Thanks (especially for taking care of SDWebImage while no-one else was active).

**Comment by mythodeia** [comment]
dont worry about it
i know everyone has limited time. :+1:

**Comment by wangjianxing** [comment]
I set imageview to nil, then update the imageView.This work for me.

`[self.imageView sd_setImageWithURL:nil placeholderImage:[UIImage imageNamed:@"mine_icon_user"]];	//set nil image`
`[self.imageView sd_setImageWithURL:[NSURL URLWithString:rowDic[@"image"]] placeholderImage:[UIImage imageNamed:@"mine_icon_user"] options:SDWebImageRefreshCached];`
