### ISSUE TITLE
Downloading images without a completion block is not pointless

### ISSUE THREAD

**Issue by ashfurrow** [rs/SDWebImage#1064]
I want to cache a few, small images for later use (I'm expecting them to be about to be downloaded, and want them cached before the user needs to see them). I tried downloading them with an empty completion block, but it looks like the library [asserts against a `nil` completion block](https://github.com/rs/SDWebImage/blob/9cc8269dcdcf7dc5fd42abb5adbd911b835bb21b/SDWebImage/SDWebImageManager.m#L114). 

> Invoking this method without a completedBlock is pointless

I feel like this is a mistake; the method in question has side-effects, side-effects which can be relied upon by outside code. Is there some other reason this is a bad idea?

**Comment by rromanchuk** [comment]
How about https://github.com/rs/SDWebImage/blob/master/SDWebImage/SDWebImagePrefetcher.h ?

**Comment by rromanchuk** [comment]
Obviously not the most elegant use case, but you get the idea 

```swift
func prefetch() {
        prefetcher.prefetchURLs(fetchedObjects?.map {
            return ($0 as! Post).url
        })
    }
```

**Comment by ashfurrow** [comment]
Oh very cool, thanks! Maybe supplement the existing comment with a pointer to use this? 😻

**Comment by rromanchuk** [comment]
@ashfurrow  there are some caveats to this bad boy though, let me try and save you some headaches 

- If you used the shared instance, it's not FIFO, as soon as you send in urls it will cancel your entire last batch
- Because it uses NSOperation `NSURLSessions` are out of the question (no support for NSURLSession priorities etc) 
- Make sure you check the defaults on max concurrent connections and don't forget to factor in your already existing  `SDWebImage`  operations
- If you are working with large images make sure you use HEAD,  and set false for `shouldDecompressImages` else your devices (especially arm64) will shutdown from memory pressure in minutes. This should be the default by the framework, but it's not :confused: 


Example defaults
```swift
SDImageCache.sharedImageCache().maxCacheSize = 300 * 1024 * 1024
SDImageCache.sharedImageCache().shouldDecompressImages = false
SDWebImageDownloader.sharedDownloader().shouldDecompressImages = false
SDWebImageDownloader.sharedDownloader().maxConcurrentDownloads = 4
```

**Comment by ashfurrow** [comment]
Super helpful – thanks @rromanchuk !
