### ISSUE TITLE
Support for non-image nsdata

### ISSUE THREAD

**Issue by hretarekar** [rs/SDWebImage#1065]
Do you have plans to provide similar caching infrastructure for just any type of data, basically NSData instead of image only?

**Comment by mythodeia** [comment]
unless @rs or @bpoplauschi have something in mind regarding caching anything NSData related, i think this library will stick to UIImage caching, at least for now.

**Comment by Mutix** [comment]
How about adding/opening the API to store (an image's) NSData directly in the cache? 

We're currently facing a use case where we extract images from a zip and want to add them to the SDImageCache. Right now, we have to create instances on UIImages with the data, then call storeImage: for each. We're dealing with several hundred images, so it would actually be useful to be able to directly store the NSData into the cache instead of having to allocate hundreds of UIImage instances.

**Comment by bpoplauschi** [comment]
It might be doable, but there are some changes required for this. feel free to work on a pull request with this

**Comment by Mutix** [comment]
Thanks, working on a PR as we speak :+1:
