### ISSUE TITLE
failedURLs is caching failed URLs and making it impossible to access images.

### ISSUE THREAD

**Issue by kentsheltongardner** [rs/SDWebImage#1091]
SDWebImageManager has a set called NSMutableSet that maintains a cache of URLs that have previously resulted in download errors. As far as I can tell, there is no way to remove a particular URL from this list to recheck the URL. At the moment, after a single failed image retrieval during a program's lifespan, all successive retrievals will also fail, even if a valid image becomes available at the desired URL.

**Comment by bpoplauschi** [comment]
We could create a method that will reset the `failedURLs` mutable set. Could you create a PR?

**Comment by cbh2000** [comment]
What about moving `failedURLs` to `SDImageCache`? That way, we can remove the URL from the failed URLs whenever the user removes the image from the image cache, or if the user replaces the image manually using `storeImage(...)`. This makes more sense to me, because this is fundamentally a caching problem, not something we should have to use `SDImageManager` for.

**Comment by molon** [comment]
Maybe failedURLs is unnecessary.  
At least I don't like it.
Now I create a category named "SDWebImageManager+AlwaysRetryFailed" ,then override "- (NSMutableArray*)failedURLs" to return nil.

Maybe It can be a switch property for developer,but not default on please.

**Comment by mythodeia** [comment]
@kentsheltongardner check with the latest build. 
Several useful error codes have been added to try and avoid adding urls in the failedurl list

**Comment by khanhshopback** [comment]
Sorry I quite don't understand. So will we have this feature?
