### ISSUE TITLE
Screen Locking when image downloading makes it impossible to download the image again

### ISSUE THREAD

**Issue by praveencastelino** [rs/SDWebImage#1128]
if you lock the screen when the image is getting downloaded, the error message what you get is 'kCFURLErrorNetworkConnectionLost'. Since this error code is not handled, the url gets added to the failedURLs list and hence the image never gets downloaded.

Error Domain=NSURLErrorDomain Code=-1005 "The network connection was lost." UserInfo=0x14510760 {NSErrorFailingURLStringKey=https://s3.amazonaws.com/xxxxxxxxxxx/qqq.jpg, _kCFStreamErrorCodeKey=57, NSErrorFailingURLKey=https://s3.amazonaws.com/xxxxxxxxxxx/qqq.jpg, NSLocalizedDescription=The network connection was lost., _kCFStreamErrorDomainKey=1, NSUnderlyingError=0x1466a6e0 "The network connection was lost."}

**Comment by mythodeia** [comment]
@praveencastelino 
i used the demo project and managed to replicate the issue you describe.
i got another error because i enabled airplane mode before i begin to download the image
```
NSURLErrorDomain Code=-1003 "A server with the specified hostname could not be found." UserInfo=0x1702e1d00 {NSUnderlyingError=0x170059c80 "A server with the specified hostname could not be found."
``` 
the url is added to the failedURL array because it satisfies the following:
```
error.code != NSURLErrorNotConnectedToInternet && 
error.code != NSURLErrorCancelled && 
error.code != NSURLErrorTimedOut
```
@bpoplauschi do you think we should add the ```NSURLErrorCannotFindHost``` or ```NSURLErrorCannotConnectToHost```
the image url was added in my case because the host could not be found as i had enabled airplane mode. What do you think?

@praveencastelino of course this can be resolved if you add the ```SDWebImageRetryFailed``` options

**Comment by mythodeia** [comment]
@bpoplauschi any updates?

**Comment by praveencastelino** [comment]
SDWebImageRetryFailed works really well for me. i hope you would accommodate 'kCFURLErrorNetworkConnectionLost' key in the future releases.
