### ISSUE TITLE
Support progressive JPEGs

### ISSUE THREAD

**Issue by chiahsien** [rs/SDWebImage#1164]
Although SDWebImage supports progressively download and display, it doesn't support progressive JPEG yet.

I've found an interesting library called [Concorde](https://github.com/contentful-labs/Concorde), is it possible to integrate it into SDWebImage?

**Comment by tuantm2014** [comment]
+1 same request

**Comment by bpoplauschi** [comment]
This sounds interesting, but we need someone to be able to work on this. And it should be after we refactor SDWebImage into 4.0

**Comment by michaelis** [comment]
Where and how would be the best way to check if the image is a progressive JPEG so that it doesn't affect performance?

**Comment by vijaytholpadi** [comment]
+1. Awaiting feature. 

When is the 4.0.0 due? So that this can be taken up?

**Comment by buithuyen** [comment]
+1

**Comment by elburro1887** [comment]
+1

**Comment by ivany4** [comment]
+1

**Comment by mave99a** [comment]
+1

**Comment by wlegate** [comment]
+1

**Comment by gate8team** [comment]
+1

**Comment by wlegate** [comment]
any update on this?

**Comment by partho-maple** [comment]
Any update on this feature ?

**Comment by partho-maple** [comment]
I think, this feature has been already implemented(as i can see now). Found the following...

`/**
     * This flag enables progressive download, the image is displayed progressively during download as a browser would do.
     * By default, the image is only displayed once completely downloaded.
     */
    SDWebImageProgressiveDownload = 1 << 3,
`

**Comment by wlegate** [comment]
@partho-maple unless something changed in the last week or so, this flag doesn't perform the desired/expected behavior as can be seen in the Concord library.

**Comment by Archivus** [comment]
+1

**Comment by tirrorex** [comment]
Any updates on that?

**Comment by Ricardo1980** [comment]
Same question here

**Comment by bpoplauschi** [comment]
I understand this is a feature that some of you need, but at this time there is no effort in implementing if from the maintainers. If anyone has the time to try it (in a PR), a lot of people would be interested. In the meantime, Concorde is probably the go-to solution.

**Comment by partho-maple** [comment]
Currently, i am working on this. Hopefully, will have some update on next few weeks.

**Comment by lucare** [comment]
+1

**Comment by dreampiggy** [comment]
This progressive-JPEG(compared to baseline-JPEG, these two image format is not actually the same) is supported via Image / IO framework. Previously (up to 4.1.2) it does not feed the JPEG data to decoder and just grab partial image. So this will not work for progressive-JPEG(In fact, this looks a bug). It was fixed in 4.1.2 and should work.(You can try your progresive-JPEG(attension again, this is not the same format as baseline-JPEG) with `SDWebImageProgressiveDownload` option.

Also, if you decide to use third-part JPEG decoding library which may help you provide more suitable decoding, you can wait 4.2 version to release(which supports custom coder) and use this [wrapper](https://github.com/SDWebImage/SDWebImageProgressiveJPEGDemo)
