### ISSUE TITLE
Why are you calling setNeedsLayout?

### ISSUE THREAD

**Issue by justme1** [rs/SDWebImage#1232]
Hi,

I'm very interested to finally understand why you call `setNeedsLayout ` in `UIImageView+WebCache.m`.
According to http://stackoverflow.com/a/10818417/314848 it doesn't seems right.

Also worth mentioning that in AFNetworking category I don't see any use of `setNeedsLayout `. https://github.com/AFNetworking/AFNetworking/blob/master/UIKit%2BAFNetworking/UIImageView%2BAFNetworking.m (you can see code here)

Please provide clear example why calling   `setNeedsLayout ` is actually needed.

Thanks.

**Comment by bpoplauschi** [comment]
Hi there. I can't find any `setNeedsDisplay` calls inside SDWebImage. Not sure where you found it.

**Comment by justme1** [comment]
Hi there,

So sorry, I meant to write `setNeedsLayout`.

`UIImage+WebCache.m` use it several times.

**Comment by bpoplauschi** [comment]
[quote from StackOverflow](http://stackoverflow.com/questions/2807137/what-is-the-relationship-between-uiviews-setneedslayout-layoutifneeded-and-lay): 
> `setNeedsLayout` is an easy one: it just sets a flag somewhere in the UIView that marks it as needing layout. That will force `layoutSubviews` to be called on the view before the next redraw happens.

Since some `UIImageView` classes or subclasses might do something custom after the image has been set, we mark the view as needing a layout. I don't know the exact reason, but I assume we do need it, as I've seen a lot of other libraries doing this. 

PS: Your [StackOverflow link](http://stackoverflow.com/a/10818417/314848) is about `setNeedsDisplay` which is another thing from our topic here.

**Comment by justme1** [comment]
Hi, 

Thanks for your comment. I'd really appreciate if someone could give a real example why it's being used in the lib.

Thanks

**Comment by adly-holler** [comment]
I agree with @justme1 this is extraneous. If `UIImageView` classes want to change their layout when an image is set, they should override `setImage:` and call `setNeedsLayout` there.

**Comment by bpoplauschi** [comment]
@rs could you answer to this question? It's been a long time, but maybe you remember

**Comment by rs** [comment]
This call to `setNeedsLayout` is mostly useful when you use the default table view cells with no placeholder image or when the placeholder image is of a different ratio than the final image.

If you don't set a placeholder image on a default cell, the cell lays out sub views like title without any room for the image at all. Thus when `SDWebImage` finish the loading of the image, the image is set on the `image` property of the cell's image view, but nothing is displayed because changing this property on the `UIImage` of default cell doesn't trigger a layout refresh.

I wanted this library to be very easy to integrate, and most of the first feedbacks were that the library wasn't working because of this issue.

**Comment by bpoplauschi** [comment]
Thanks @rs for responding to this.
