### ISSUE TITLE
sd_setImageWithURL returning wrong image URL completion.

### ISSUE THREAD

**Issue by rraghul** [rs/SDWebImage#1286]
(UIImage *image, NSError *error, SDImageCacheType cacheType, NSURL *imageURL)

When calling Multiple URLs in collection view its not providing with the correct image and its ImageURL

**Comment by mythodeia** [comment]
@rraghul you can replicate it in the demo project with your urls?

**Comment by rraghul** [comment]
i am not supposed to share the urls but these are indeed happening

**Comment by mythodeia** [comment]
no need to share...just use the urls in the demo project and test again. the demo project uses a tableview. I am only asking this because what you are describing is a fundamental feature and everyone would have the same issue. Are you sure you are not having cell re-use issues with your collection view?
Do you nullify the image on your ```prepareForReuse``` method in your collectionviewcell subclass?

**Comment by mythodeia** [comment]
@rraghul any updates on this?
