### ISSUE TITLE
using SDWebImage for SVG images

### ISSUE THREAD

**Issue by sashkasashkin** [rs/SDWebImage#1365]
Hi! 
How I can use SDImageCache to cache SVG image?
Is it real to use SDWebImage to download SVG? Now I use another library but I need to cache SVG-image.

Thank you.

**Comment by sallyahmed** [comment]
any update the same here ?

**Comment by mythodeia** [comment]
svg images are not supported yet

**Comment by zhangao0086** [comment]
Any updates on this one?

**Comment by bpoplauschi** [comment]
No updates - I don't think anyone is working on this

**Comment by bpoplauschi** [comment]
Look at some dedicated SVG lib, like SVGKit.

**Comment by dreampiggy** [comment]
You can use [SVGKit](https://github.com/SVGKit/SVGKit) to create a custom coder, really easy.
To know how to build a custom coder, see [Custom Coder](https://github.com/rs/SDWebImage/wiki/Advanced-Usage#custom-coder-420)

**Comment by SergeyDevUA** [comment]
any update?

**Comment by dreampiggy** [comment]
@SergeyDevUA @sashkasashkin  Since we have the coder plugins, it's not hard to write one by yourself.

But anyway, if you still prefer to use a out-of-box SVG support. I can spend little time to write one.

At first, I suggest to use [SVGKit](https://github.com/SVGKit/SVGKit) to build the coder plugin because when I search github, it contains the most stars. However, after I run the demo project and found that this repo is really ancient. And it contains bug don't render alpha-channel SVG well. And it's really buggy to be compatible for latest iOS firmware.  So I will not use that.

Then I found that there is one repo [SwiftSVG](https://github.com/mchoe/SwiftSVG) with more than 1000 stars. I will try that. Note since this is s Swift framework, user who still only use Objective-C should use the Swift-to-Objective-C bridging way, and may increase their binary size because of Swift's runtime library. But anyway, it the only framework I found that it's not so buggy :)

**Comment by dreampiggy** [comment]
Update... After I create another demo code, I found that [SwiftSVG](https://github.com/mchoe/SwiftSVG) is buggy as well. When using the official demo code to render this SVG: https://upload.wikimedia.org/wikipedia/commons/1/14/Mahuri.svg, the application die and result a 100% CPU nearlly 10 seconds. I don't think it's good enough for production.

So let me try some other choice, or I can firstlly show your demo framework using [SVGKit](https://github.com/SVGKit/SVGKit). At least it will not die when loading complicated SVG files.

**Comment by dreampiggy** [comment]
@SergeyDevUA @sashkasashkin I create one simple wrapper framework [SDWebImageSVGCoder](https://github.com/dreampiggy/SDWebImageSVGCoder), please have a try and provide some feedback. The `Podfile` may looks like this

```ruby
pod 'SDWebImageSVGCoder`, :git => 'https://github.com/dreampiggy/SDWebImageSVGCoder.git', :branch => 'master'
```

----


If you still want to use [SwiftSVG](https://github.com/SVGKit/SVGKit) this library for actual SVG parsing, you can also try this one [SDWebImageSVGCoder-Swift](https://github.com/dreampiggy/SDWebImageSVGCoder-Swift). The `Podfile` is the same one.

**Comment by dreampiggy** [comment]
@SergeyDevUA @sashkasashkin Any feedback ?

Currently I only decode the SVG images to the bitmap image (fixed size), it's not a vector format and allows you to resize it into any size without losing the detail.

If you use the `SVGKFastImageView` or `SVGKLayeredImageView` to support vector images and resizing, maybe I can also update to provide a demo.

**Comment by satishVekariya** [comment]
iOS support pdf vector image!!

**Comment by dreampiggy** [comment]
@satishVekariya
See https://github.com/SDWebImage/SDWebImagePDFCoder
