### ISSUE TITLE
Cached Images Broken on 3.7.4

### ISSUE THREAD

**Issue by realaboo** [rs/SDWebImage#1422]
When upgrading from 3.7.3 to 3.7.4, something was broken. Some cached images could not been displayed but those files were still on disk. Reverting back to 3.7.3 solves the problem.

May be related to:
https://github.com/rs/SDWebImage/pull/976

I haven't dug into it yet. Just in case anybody else has the same issue.

Will be back a little bit later after debugging.

**Comment by adomanico** [comment]
This is definitely an issue. Our production users are seeing incorrect images for the correct cache key

**Comment by adomanico** [comment]
Was able to dig in a little bit and confirm that the keys are correct but the image is incorrect

**Comment by Panajev** [comment]
This seems like a dealbreaker for people looking to update to 3.7.4, have you guys found a workaround that can be applied app side to mitigate this problem? 
Flushing the cache only the first time the app is started with the new update patched in maybe?

**Comment by bpoplauschi** [comment]
Guys, I think I understand the issue and it's probably related to #976 because we added the extension to the cached file name. But I don't see how this could break things for the users. Worst case, it should just redownload the images that are in the cache, but their name is the old one (without the extension).

**Comment by bpoplauschi** [comment]
I've done a bit of debug and things look fine. Do you have any problematic URLs that could lead to a wrong filename?

It makes sense for me for the 3.7.4 version not to load the images cached by previous versions, because of this change. It this a problem? I think not, the library can download them again. If it is a problem, then we could maybe create a backwards compatible mechanism so we can still load those images.
i.e. look for key.jpg, if it fails, fallback to key.

**Comment by realaboo** [comment]
In most cases this should be fine if the images could be downloaded again. But in my case I use SDWebImageCache also as permanent file storage and the images are volatile, they are probably not there anymore. Would be fine if have fallback lookup or rename the files automatically.

**Comment by bpoplauschi** [comment]
Fixed by fca618f - Added a fallback for #976 so that if there are images saved with the old format (no extension), they can still be loaded.
I will release a 3.7.5 patch. Please let me know if this fixes the issue.
