### ISSUE TITLE
Extra instance of SDWebImageManager being used in SDWebImagePrefetcher

### ISSUE THREAD

**Issue by wyland** [rs/SDWebImage#1445]
The `SDWebImageManager` has a `sharedManager()` singleton, which makes it easy to implement the `SDWebImageManagerDelegate` protocol.

However it appears that the `SDWebImagePrefetcher` has an additional instance of the `SDWebImageManager` which means you need to assign and keep track of two delegates:

```
    SDWebImageManager.sharedManager().delegate = self
    SDWebImagePrefetcher.sharedImagePrefetcher().manager.delegate = self
```

Why doesn't the prefetcher use the `sharedManager()` instead of initializing another instance of the manager?  Or would it better to move this delegate elsewhere so that it isn't tied to instances of the manager?

Thanks

**Comment by bpoplauschi** [comment]
I think the idea here was to separate the images that need to be downloaded now of the ones that are being prefetched, so using 2 instances of `SDWebImageManager`. The code you posted looks ok, you should be able to set the same delegate for 2 manager instances.

**Comment by minoue10** [comment]
I know this is closed, but +1 on this.

We define the `cacheKeyFilter` on the `SDWebImageManager.sharedManager`, but the images I was prefetching using the `SDWebImagePrefetcher` weren't caching for when I actually needed them. I realized that because the `SDWebImagePrefetcher` uses its own instance of `SDWebImageManager`, we realized we have to redefine the `cacheKeyFilter` so that the two `SDWebImageManager`s are using the same filter to generate the unique image file names for caching.

Not a huge deal for us, but it took longer than I expected to figure this out.

**Comment by bpoplauschi** [comment]
@wyland @minoue10 I don't know the exact reason for having the 2 instances of `SDWebImageManager`, but my guess is it's related to performance, having a dedicated manager for pre-fetching that is lower in priority than the downloads needed at that time in particular.
Maybe @rs can bring some light ... if you remember :)

CC @mythodeia @skyline75489
