### ISSUE TITLE
#enhancement# should add a global option setter?

### ISSUE THREAD

**Issue by DeveloperPans** [rs/SDWebImage#1509]
### Description

After iOS 9, more and more app connect server with HTTPS. So we have to write follow code again and again...

```
    [self.avatarImage sd_setImageWithURL:[ZNWSUtil urlWithPath:entity.Poster]
                        placeholderImage:[UIImage imageNamed:@"CMGBigPoster"]
                                 options:SDWebImageAllowInvalidSSLCertificates];
```
### Enhancement

just like AFNetWorking, could you provide a API, in SDWebImageDownloader  like that:

```
@property (assign, nonatomic) SDWebImageDownloaderOptions option;

```

so that we can set default option once,effect everywhere.

method option set like `- (void)sd_setImageWithURL:(NSURL *)url placeholderImage:(UIImage *)placeholder options:(SDWebImageOptions)options;
` will cover the globe option.

**Comment by bpoplauschi** [comment]
Not sure about this. The idea was you can have multiple download sources, each one with their own settings. That's why `SDWebImageDownloaderOptions` is passed along with every request. So one request can ask for progressive jpeg and another one use HTTP auth and so on. Not sure how would a global set of settings work. We might make the options passed by param override the ones from the class options, so therefore needing to pass 0 as options so the class options are in effect, but I'm not convinced.

**Comment by mythodeia** [comment]
i agree with @bpoplauschi. Since we might have multiple download sources we can set up each one individually with their own settings. I will close this for now. if you have other thoughts please reopen
