### ISSUE TITLE
SDWebImagePrefetcher doesn't call completion block

### ISSUE THREAD

**Issue by armandsLa** [rs/SDWebImage#1521]
If you load multiple urls in SDWebImagePrefetcher and download any of them using SDWebImageManager at the same time, SDWebImagePrefetcher completion block never gets called.

**Comment by hsncr** [comment]
any workaround?

**Comment by dreampiggy** [comment]
This is actually solved by current implementation because SDWebImageDownloadOperation keep a callbacks array. Each callback will be called.

When you call two equal urls for `-[SDWebImageManager loadImageWithURL:]`, this will behave as you want.

SDWebImagePrefetcher -> SDWebImageManager -> Reused Operation -> Add Callbacks
