### ISSUE TITLE
MemCache image cost

### ISSUE THREAD

**Issue by yaliashkevich** [rs/SDWebImage#1591]
Just a question:

Why image cost calculation for memory cache uses image.scale two times?

```
FOUNDATION_STATIC_INLINE NSUInteger SDCacheCostForImage(UIImage *image) {
    return image.size.height * image.size.width * image.scale * image.scale;
}
```

**Comment by yaliashkevich** [comment]
My goal is to setup memory cache limit for let's say ~100mb. How should I use setMaxMemoryCost method achieve this. What is approximate relation between result of SDCacheCostForImage(UIImage *image) and actual size of memory taken by image?
```
- (void)setMaxMemoryCost:(NSUInteger)maxMemoryCost {
    self.memCache.totalCostLimit = maxMemoryCost;
}
```

**Comment by bpoplauschi** [comment]
In `SDCacheCostForImage` we multiply the scale 2 times because each dimension contains it - both the width and the height. It basically returns the number of pixels. If you have a 200x300 image @2x, then it basically has 400x600 pixels = 240000 pixels.

As stated in the doc `The cost function is the number of pixels held in memory.` this means you have to compute the number of pixels that can be stored in 100MB. I think dividing it by 8*4 (8 bytes per chanel * 4 channels RGBA) will give you the number of pixels that can be stored in 100MB. This means you should set: 3,125 * 1024 * 1024 = 3276800 pixels. Does this make sense?

**Comment by yaliashkevich** [comment]
It`s clear about image.scale now.

But what memory is taken for uncompressed image pixel, isn't it  32-bit RGBA, so each pixel take 4 bytes? So i can set totalCost = {maxMemory} / {4 bytes per pixel} = 100*1024*1024 / 4 = 26214400 ?

**Comment by bpoplauschi** [comment]
@yaliashkevich you're right: 32-bit per pixel (not bytes as I said). Your calculation is correct.
