### ISSUE TITLE
EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by lixiang1994** [rs/SDWebImage#1650]
### New Issue Checklist
- [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
- [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
- [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none
### Issue Info

| Info | Value |
| --- | --- |
| Platform Name | e.g. ios |
| Platform Version | e.g. 9.3 |
| SDWebImage Version | e.g. 3.8.1 |
| Integration Method | e.g. cocoapods |
| Xcode Version | e.g. Xcode 7.3 |
| Repro rate | e.g. sometimes 30% |
| Repro with our demo prj | e.g. does it happen with our demo project? |
| Demo project link | e.g. link to a demo project that highlights the issue |
### Issue Description and Steps

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

<img width="1400" alt="qq20160818-0 2x" src="https://cloud.githubusercontent.com/assets/13112992/17760570/4794358c-6533-11e6-90ad-e51a6dfceb95.png">
<img width="1400" alt="qq20160818-1 2x" src="https://cloud.githubusercontent.com/assets/13112992/17760571/48db3e40-6533-11e6-81cb-ac18fc87c6f9.png">

**Comment by sunbohong** [comment]
Can you supply a url of your image?

**Comment by lixiang1994** [comment]
Picture in the news list , Seems to have no relationship with url , 2.7.6 the following has never happened .

**Comment by bpoplauschi** [comment]
@lixiang1994 what's the description printed in the console? It should say something about the error

**Comment by 6david9** [comment]
I found some crash was by calling block like this:

    if (self.completedBlock) {
      self.completedBlock(nil, nil, error, YES);
    }

the NSURLSession delegate was not calling in the main thread, and the other thread cancel the operation.
After checking self.completedBlock, operation was canceled and self.completedBlock assigned to nil, calling nil as a block will crash. 
And the crash address will always be 0x10.

this can be fix like this:    
    BlockType completedBlock = self.completedBlock
    if (completedBlock) {
        completedBlock(nil, nil, error, YES);
    }

**Comment by bpoplauschi** [comment]
Can someone create a PR with those fixes? I don't know to which pieces of code they apply

**Comment by dreampiggy** [comment]
This should be fiex in SD 4.0. I checkout the 3.7.6 version and agree that there may be a race condition when you enter the block and prepare to call the block, but another thread cancel the task(which will call `self.completedBlock = nil;`) 

The code is here: https://github.com/rs/SDWebImage/blob/3.7.6/SDWebImage/SDWebImageDownloaderOperation.m#L244

This fix will work on 3.7.6 version because the block is grabed in advance and will not be affected by that `self.completedBlock = nil;`(block property attribute is `copy`). But since we released 3.7.6, maybe someone could checkout `3.7.6` tag and create an bug fix release?

**Comment by dreampiggy** [comment]
Need we release a patch release based on 3.7.6 such as 3.7.7 ? To do this, we need a extra branch such as `3.7.x-compat` checked out from `3.7.6` tag and merge the fix pull request(I create one [here](https://github.com/rs/SDWebImage/compare/3.7.6...dreampiggy:fix_3.7.6_EXC_BAD_ACCESS)) to that branch then add an new `3.7.7` tag because 3.8.x drop the iOS 5-6 support. (Oh great the backwards compatibility 😞 )
