### ISSUE TITLE
[Question] Is it necessary to call `SDScaledImageForKey` method?

### ISSUE THREAD

**Issue by welsonxue** [rs/SDWebImage#1793]
When access image from disk cache, it will call the method `SDScaledImageForKey` to rescale the image. But why using the `[UIScreen mainScreen].scale`, it really confuse me.

E.G. Suppose i get an image from the net, and the image real size is 60 x 60, then different device will get different image size (since iPhone6 will get 30x30 and iPhone 6 plus will get 20 x20), if the display imageView is `sizeToFit`, then it will get the wrong display size. How can I solve this problem, or i use it in a wrong way?

**Comment by bpoplauschi** [comment]
The reason for doing this (and the library is doing it for quite some time) is this:
- if you display a 60x60 image on an iPhone 6 Plus in a 60x60 frame, the image will be pixelated. It's the way retina works. You need an image 3 times that size to look good. That's why we split the size by the scale, so we get an image that looks good.

If you really need to display at the original resolution, ignoring scale, I guess we could add a new option like SDWebImageIgnoreScale that when set, will just ignore the scale.
Anyone interested in making this into a PR?

**Comment by welsonxue** [comment]
Thanks for your reply, I think I'd like to make this into PR later. : )


发自网易邮箱大师
On 02/09/2017 15:13, Bogdan Poplauschi wrote:

The reason for doing this (and the library is doing it for quite some time) is this:

if you display a 60x60 image on an iPhone 6 Plus in a 60x60 frame, the image will be pixelated. It's the way retina works. You need an image 3 times that size to look good. That's why we split the size by the scale, so we get an image that looks good.

If you really need to display at the original resolution, ignoring scale, I guess we could add a new option like SDWebImageIgnoreScale that when set, will just ignore the scale.
Anyone interested in making this into a PR?

**Comment by dreampiggy** [comment]
If you are always using a fixed size `UIImageView`, and use any scale `contentMode`, whatever scale is OK because you always scale :)

But, if you use a `UIImage` and call `[UIView sizeToFit]`. Then issue come.

For example, if your device scale is @2x. There is a image(100x100). If you specify it's a @1x image. Then `sizeToFit` will cause imageView to 200x200pt.
But if you specify it's a @2x image. Then `sizeToFit` will cause imageView size to 100x100pt.

There are also many other impact, such as Core Animation, if you specify the wrong scale, the animation will looks strange. So we should better try to get the original image scale from URL or file path name :)

**Comment by dreampiggy** [comment]
Maybe in 4.x we have no ways to change (Since `SDWebImageOptions` is a Objective-C enum, which can only represent bool value :))

In 5.x, we can. See #2266

**Comment by dreampiggy** [comment]
In 5.x, you can use `SDWebImageContextImageScaleFactor` to specify the scale factor you desired. It works from View Category, Downloader, Cache and Coder. So this PR can be closed now. Wait for 5.0.0 release. :)
