### ISSUE TITLE
Webp causes memory to surge

### ISSUE THREAD

**Issue by dengbin9009** [rs/SDWebImage#1885]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | e.g. ios / tvos
 Platform Version        | e.g. all
 SDWebImage Version      | e.g. 4.0.0
 Integration Method      | e.g. cocoapods
 Xcode Version           | e.g. Xcode 8.3.2
 Repro rate              | e.g. all the time (100%) 
 Repro with our demo prj | e.g. MayBe
 Demo project link       | e.g. link to a demo project that highlights the issue

### Issue Description and Steps

I have been using SDWebImage, now I'm going to get my App to support webp images.
I found that webp format images will cause my App memory to take up memory, resulting in a crash.
![4cc58bd5-845c-4915-955b-7e9503e71782](https://cloud.githubusercontent.com/assets/3061194/25700093/a20c2b5a-30f8-11e7-9abb-5bc4ebe140f1.png)

SDWebImage take up about 270M memory, why is this problem?
If the picture is jgp format there is no such problem

**Comment by mythodeia** [comment]
How big are the images you are using?

**Comment by EugeneGoloboyar** [comment]
I can suggest you to load images lazily (only when user explicitly need it).
It might cause some delay for big images but suppose you try to preload some heavy images.

it is good to look into SDImageCache and SDWebImageDownloader configuration. 

especially at shouldDecompressImages (default is "YES") 

SDWebImageDownloader.shared().shouldDecompressImages = false
SDImageCache.shared().config.shouldDecompressImages = false
SDImageCache.shared().config.shouldCacheImagesInMemory = false

this might be helpful

also try to clear cache when screen with images disappear and test your app on different devices 
(as old devices have less RAM memory)

**Comment by dengbin9009** [comment]
@mythodeia 
all image like :
```
    https://imgqn6.fruitday.com/images/2017-04-28/7cf04bd9965b0c11e4b47c32430d4aec.webp
    https://imgjd4.fruitday.com/images/2017-05-03/dca5894445c21e8c409a12b6c12a0263.webp
    https://imgjd2.fruitday.com/images/2017-04-24/6870da70fd115f886eda5f1c333475d9.webp
```

There are about 100 pictures. 

The problem is the same picture if replaced by jgp format there is no such problem

This question bothered me for a long time and I am eager to get your help！

thx！

**Comment by dengbin9009** [comment]
@EugeneGoloboyar 
As you said, I have done this, but it does not work for me.

In version 4.0.0, I can not change the config in SDImageCache,So I have tried to change the source code

```
[[SDWebImageDownloader sharedDownloader] setShouldDecompressImages:NO];
```

**Comment by dreampiggy** [comment]
First, this is not memory leak issue but just the case that the UIImage instances with bitmap data consume a lot of memory.

Currently SDWebImage's WebP decode the image data to UIImage(CGImage) instance with raw bitmap through `libwebp` because Core Image does not support WebP format and CGImageSource will fail. So it will decoded raw webp image data(which use VP8 compressed codec and should be smaller than raw bitmap) to CGImage by `CGImageCreate` using the bitmap vector(which may use 32 * width * height * RGBA memory for each WebP frame). This happed during the download completed and before the set the image to UIImageView.

But for JPEG format, that CGImage is create with `CGImageSourceCreateImageAtIndex`, this is lazily load CGImage unlike that `CGImageCreate` (CGImage internal will hold reference to the raw JPEG data without decoding and decompressed) and the actual decoding process is under the rendering progress of UIImageView after you set `imageView.image = xxx` and go to next draw call). This may take more CPU while rendering but it's good for memory (Space and time balance problem, you know). 

Moreover(if you're interested in performance and go on, or just ignore these...), JPEG is static image format and it decoed use the hardware so this may not become the bottleneck. But WebP can be animte image, which will cause a huge CPU load during rendering and reduce the frame rate. So we choose to decoed it on the background thread in advance(Which indeed prefer the speed over space). Therefore this may cause memory issue if you load an big animated WebP. This is nearly the same method for GIF before SD 4.0. On 4.0, we introduce FLAnimatedImage because it use the raw GIF data and decoded and cached with an range during rendering (like TCP slide window) on that FLAnimatedImageView layer with CADisplayLink. This is an balance of speed and space. But sadly currently our WebP is on an UIImageView category but not subclass, so we could not change its' own behavior. You can check there [code] to learn (https://github.com/Flipboard/FLAnimatedImaget/blob/master/FLAnimatedImage/FLAnimatedImage.m#L480) or the similar project like [Gifu](https://github.com/kaishin/Gifu)

Since currently SD still use WebP support as an `UIImageView` category so we could not do further performance optimise. But we could considerate to do something change (Maybe create an `SDAnimatedImageView` or drive FLAnimatedImage to support WebP) optimise like the description above. Or maybe all this suck could be changed if UIKit support WebP/GIF natively in the future.

Also, please do not close this issue to allow people to find more optimization the situation 😃
