### ISSUE TITLE
I found the new memory issue.

### ISSUE THREAD

**Issue by tiwariammit** [rs/SDWebImage#1889]
![screen shot 2017-05-05 at 3 31 59 pm](https://cloud.githubusercontent.com/assets/22368948/25740936/58794d8c-31a8-11e7-8f6a-4a0b304f027e.png)

**Comment by mythodeia** [comment]
@tiwariammit this does not say much. can you replicate it in the demo project? how big are the images you are trying to load? which version of this library are you using?

**Comment by dengbin9009** [comment]
@tiwariammit I met the same problem as you ,Did you solve this problem?
#1885

**Comment by tiwariammit** [comment]
No i didn't solved yet. I found on latest version

On Tue, May 9, 2017 at 7:24 AM, FlyingChickenWings <notifications@github.com

**Comment by dengbin9009** [comment]
@tiwariammit
 Is there the problem in the old versions?

**Comment by tiwariammit** [comment]
Nope. Its on the current version.

**Comment by dreampiggy** [comment]
Could you please provide more information about this issue. Since you does not fllow the template(including SD ver, Xcode ver, Platform ver, etc).

I checked the SD `master` branch code, there are no obvious leak. (That colorspaceRef is retrived by CGImage or created with CFAutorelease). If you provide more details, we can find the reason here.
