### ISSUE TITLE
why not decode image with alpha ?

### ISSUE THREAD

**Issue by wangdongabc** [rs/SDWebImage#2008]
CGImageRef imageRef = image.CGImage;

    CGImageAlphaInfo alpha = CGImageGetAlphaInfo(imageRef);
    BOOL anyAlpha = (alpha == kCGImageAlphaFirst ||
                     alpha == kCGImageAlphaLast ||
                     alpha == kCGImageAlphaPremultipliedFirst ||
                     alpha == kCGImageAlphaPremultipliedLast);
    // do not decode images with alpha
    if (anyAlpha) {
        return NO;
    }

**Comment by dreampiggy** [comment]
You are misunderstanding by that `decode` word. This should be named `decompress` or `decode before rendering`. This `shouldDecodeImage` method is used to that `UIImage+ForceDecode` category.

`UIImage` is just an wrapper to `CGImage`. When you use that `+[UIImage imageWithData:]` to create an UIImage instance, the image data will not decode to image bitmap immediately(You won't see any memory increate when you call this method). Instead, the underneath `CGImage` instance is just created with `CGImageSourceCreateWithDataProvider` and it will be decoded the first time the UIImageView rendering(You can learn this behavior from other references and I will not talk detail implementation here). 

But sometimes we need to decompressed first before UIImageView rendering. This is an feature that can help you increase frame rate(because the rendering process do not need decoding CPU usage) but this also means you need extra memory before you set UIImage to UIImageView. So we have that `UIImage+ForceDecode` category.

For historic reason, the ForceDecode process happend for alpha PNG. But there seems some bugs related. So then it drop the process for alpha image and only decode non-alpha images. You can also set `shouldDecompressImages` to NO to disable this feature totally.
