### ISSUE TITLE
When I have different transform needs, I need to subclass SDWebImageManager, is this right?

### ISSUE THREAD

**Issue by Josscii** [rs/SDWebImage#2014]
In my project, I have to transform same image to serval forms, like cornerRadius = 10 or 15, or blur that image before caching, and of course, I do want to cache it separately, but the only way I found to solve this problem is to write multiple subclass of SDWebImageManager, is there any easy way?

sample code showed as follows:

```
class BlurImageManager: SDWebImageManager {

    static let shared = BlurImageManager()
    var imageLayer = CALayer()
    
    init() {
        super.init(cache: SDImageCache.init(namespace: "xxxx"), downloader: SDWebImageDownloader.shared())
        delegate = self
        imageLayer.contentsGravity = "resizeAspectFill"
        imageLayer.cornerRadius = 5
        imageLayer.masksToBounds = true
    }
}

extension BlurImageManager: SDWebImageManagerDelegate {
    func imageManager(_ imageManager: SDWebImageManager, transformDownloadedImage image: UIImage?, with imageURL: URL?) -> UIImage? {
        let image = image?.blurDarkImage()
        
        let size = CGSize(width: kScreenWidth-20, height: 150)
        
        UIGraphicsBeginImageContextWithOptions(size, false, 0)
        let context = UIGraphicsGetCurrentContext()!
        
        imageLayer.frame.size = size
        imageLayer.contents = image?.cgImage
        
        imageLayer.render(in: context)
        
        let output = UIGraphicsGetImageFromCurrentImageContext()!
        UIGraphicsEndImageContext()
        
        return output
    }
}
```

**Comment by dreampiggy** [comment]
A better practice is to create an delegateManager to dispatch all the delegate method call to what you need.

```
```

**Comment by dreampiggy** [comment]
First. A delegate do not need to subclass `SDWebImageManager`. You can use all the class which just conform the `SDWebImageManagerDelegate`.

```objectivec
@interface MyObject : NSObject <SDWebImageManagerDelegate>
@end
```

So you can just place that `cornerRadius` or some property as configuration in your own class and implement the delegate method.

**Comment by Josscii** [comment]
You may not fully understand my problem, I do know `A delegate do not need to subclass SDWebImageManager`, but the problem is that  SDWebImageManager's singleton can have only one delegate, but I have multiple transform style to one image and cache it separately, can you come up some ideas about this case?

**Comment by dreampiggy** [comment]
For this use case. Maybe you can try to create an `delegate manager` which hold multiple NSObject<SDWebImageDownloadDelegate` instance. And set this `delegate manager` to `SDWebImageManager.sharedManager.delegate`. Then, when the `delegate manager` receive any method call, dispatch it to all the delegates item and choose one to return. The returned one will be cached (Like the naive code [here](https://stackoverflow.com/questions/14278857/delegation-to-multiple-objects)). This can simulate multi-delegate design pattern.

Can this achieve your problem ?

**Comment by Josscii** [comment]
I don't think that can solve it, cause for one image, SDWebImageManager's singleton would just cache it once in one place, while I do want to cache all transformed image of that image to disk, and use it in its right place.

Maybe the core issue is that I want the SD do the most things for me, like download(which is ok to use the shared instance), cache(which is not ok for this case to use the shared cache instance), find cache..., and then I would just use the api on SDWebImageManager's to load image:

```
- (nullable id <SDWebImageOperation>)loadImageWithURL:(nullable NSURL *)url
                                              options:(SDWebImageOptions)options
                                             progress:(nullable SDWebImageDownloaderProgressBlock)progressBlock
                                            completed:(nullable SDInternalCompletionBlock)completedBlock;
```

**Comment by dreampiggy** [comment]
Since this not the common case (Download one image and cache for multiple format), I think you could try yourself to find a better solution. Maybe you can just directly call `-[SDImageCache storeImage:imageData:forKey:toDisk:completion:]` in the `delegate manager` before return to save all the delegate returned image to cache.

Moreover, I think this should not be an issue but more like some business logic or usage, maybe it's not suitable to discuss on repo issues. 😴

**Comment by Josscii** [comment]
sorry, I will close it.

**Comment by dreampiggy** [comment]
Hey. I'm creating a related new feature request. #2115 

Previouly our category methods are hard-coded to use shared image manager. But now I provide a way to pass your custom manager even for these category methods. So you can set different manager for different imageView without override global one. 

So that you can create each manager for each type of your transform. Then call the specify one to use. Can this solve your problem ?

**Comment by Josscii** [comment]
let me check it, thanks for your nice work, I'll feed back!

**Comment by Josscii** [comment]
@dreampiggy I watched your implementation and thought about it, I don't know If it is a good solution to this common problem, when you want to download a image once, while you want to transform it to multiple style,  and even cache all the transformed image separately.
You might see the Swift image load framework [kingfisher](https://github.com/onevcat/Kingfisher/wiki/Cheat-Sheet), it has a `Processor` options to specify, and it will automatically transform and cache it separately. Thanks your effort again.

**Comment by dreampiggy** [comment]
@Josscii I see. Kiingfisher use the benefit from Swift's struct. However in Objective-C, we need to create instance each time.

In my opion, actually we can do the same things like those, but looks more complicated. Because these two framework's have a different design pattern and kingfisher do not have such a historic limit.

I add this pull request because I need to seperate cache path for different image request. But I do not want to directly use `SDWebImageManager` API to build from scratch.


```objective-c
    UIImageView *imageView1;
    UIImageView *imageView2;
    SDImageCache *cache1 = [[SDImageCache alloc] initWithNamespace:@"cachePath1"];
    SDImageCache *cache2 = [[SDImageCache alloc] initWithNamespace:@"cachePath2"];
    SDWebImageDownloader *downloader = [SDWebImageDownloader sharedDownloader];
    SDWebImageManager *manager1 = [[SDWebImageManager alloc] initWithCache:cache1 downloader:downloader];
    SDWebImageManager *manager2 = [[SDWebImageManager alloc] initWithCache:cache2 downloader:downloader];
    manager1.delegate = self; // is a delegate instead of block, so in the `imageManager:transformDownloadedImage:withURL:`, you need a switch case to check manager instance, and cache the different transformed image
    manager2.delegate = self;
    [imageView1 sd_internalSetImageWithURL:url1 placeholderImage:nil options:0 operationKey:nil setImageBlock:nil progress:nil completed:nil context:@{SDWebImageInternalCustomManagerKey : manager1}];
    [imageView2 sd_internalSetImageWithURL:url2 placeholderImage:nil options:0 operationKey:nil setImageBlock:nil progress:nil completed:nil context:@{SDWebImageInternalCustomManagerKey : manager2}];
```

And also, in SD4.2, we introduce a `SDWebImageCoder` to build your custom coder. The methods are called from global queue so you can just directly use `SDImageCahce` to cache whatever you want for whatever times for single download image.

**Comment by Josscii** [comment]
@dreampiggy yes, I totally understand your idea, we have to manage multiple manager because of the historic limit. One remain problem is that, if we want to download one image and transform it to multiple style and cache it separately, we might have to download it multiple times?

**Comment by dreampiggy** [comment]
@Josscii No...Actually it would be cached from `SDImageCache`. It's a memory-disk cache :)

And as I told above, if you are `Creative` enough. You can directly call `SDImageCahce` API to save that transformed image to cache anytime. For example, in the delegate methods call. It's a little trick but maybe sometimes we have to use that.

**Comment by Josscii** [comment]
Ok, I got it. Thanks.

**Comment by sainttail** [comment]
I think sometime we want to have separate process to transform image to whatever we want per uiimageview

I think method signature like [this](https://github.com/pinterest/PINRemoteImage#download-and-process-an-image) is very easy to use.

**Comment by dreampiggy** [comment]
@sainttail See #2219 and [5.x](https://github.com/rs/SDWebImage/blob/5.x/SDWebImage/SDImageTransformer.h)...

I'm doing some documents related stuff. And maybe I need to ask the @bpoplauschi to release 5.0.0-beta soon. It takes too long time.

**Comment by sainttail** [comment]
Oh, thank for your response, I've never seen that PR.

**Comment by dreampiggy** [comment]
@Josscii See 5.0 feature [Image Transformer])(https://github.com/rs/SDWebImage/pull/2219). It's what you espect for `Kingfisher-like Processor`. It allow you to chain the pipeline transformer. It works for cache & manager level. It provide many built-in image process util categories.

The 5.0 beta release is delayed because of many issue (personnel issue, code issue, communicate issue as well). I hope it can be released before Jully. But it all depends.

**Comment by Josscii** [comment]
@dreampiggy 👌, nice work, I ignored the above messages, sorry.

**Comment by Josscii** [comment]
@dreampiggy I looked into 5.0 feature, and I got a question, why didn't you query the memory cache using the transformed key [here](https://github.com/rs/SDWebImage/blob/997bf8ff3582c3d9408fe1ec65470595b2f787a4/SDWebImage/SDImageCache.m#L348) ?
