### ISSUE TITLE
Gif doesn't work when I use `cacheMemoryOnly` option

### ISSUE THREAD

**Issue by hossamghareeb** [rs/SDWebImage#2076]
### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name                 | iOS
 Platform Version              | iOS 10
 SDWebImage Version     |4.1
 Integration Method         | carthage
 Xcode Version                 | Xcode 8
 Repro rate                        | all the time (100%) 

### Issue Description and Steps
I'm using SDWebImage for gif and normal images using `FLAnimatedImageView`. Everything works fine till I added an option to use `cacheMemoryOnly`. At that case, gif doesn't work. It shows only one frame! 

Code I'm using right now:

```
animatedImageView.sd_setImage(with: url, placeholderImage: nil, options: .cacheMemoryOnly) { (img, error, _, _) in
            
}
```

**Comment by dreampiggy** [comment]
Yes. Known behavior since that `FLAnimatedImageView` need the raw NSData to play GIF but not UIImage. So the first time you download that image from network and we have NSData to feed `FLAnimatedImageView`. Then, if we grab the cache from disk, the data is nil and we could only show the first frame UIImage.

Currently 4.1.x seems have no choice to solve this issue. Maybe we should try another way to fit this.(Such as make a wrapper to that `FLAnimatedImage` since it's not subclass from UIImage ?) Currently I recommaned to open this option and set a limit on cache size through `SDImageCacheConfig`.

On our developing 4.2 version, we can now support all UIImaegView with GIF as well through custom coders. This may solve this issue because if we have no data, we can feed `FLAnimatedImageView` with UIAnimatedImage. But I think it's not good enough because it lose the performance benefit from `FLAnimatedImage` itself.

Keep this issue on until we can find better solution.

**Comment by dreampiggy** [comment]
If you're still in concern about this issue, try to see #2140 about our implementation which replace the `FLAnimatedImage` by our own `SDAnimatedImage`, which is a UIImage subclass and can cached into memory. 😀

**Comment by dreampiggy** [comment]
It seems that #2181 use a tricky way(Associatd object to bind `FLAnimatedImage` to the `UIImage` stored in memory cache). This may solve the problem.

To tell the truth, FLAnimatedImage have some limitation on animated image rendering. So in 5.x we'll use our `SDAnimatedImageView` instead. The FL category may still be provided by some other ways (Like seperate that subspec to another repo)
