### ISSUE TITLE
网络加载jpg图片时，CGImageSourceCopyPropertiesAtIndex 这个方法在DEBUG环境下每次都崩溃

### ISSUE THREAD

**Issue by mengzhu716** [rs/SDWebImage#2088]
CFDictionaryRef properties = CGImageSourceCopyPropertiesAtIndex(imageSource, 0, NULL);
具体原因  具体原因我也不清楚，目前有一张图片会出现此问题
图片链接：http://p1.img.cctvpic.com/photoAlbum/page/performance/img/2017/10/27/1509090732557_611.jpg

**Comment by dreampiggy** [comment]
Exception: `XML parsing failure`

This may because that EXIF metadata is not valid format. Maybe you should try to repairt this images' EXIF metadata.
For client, I think this method is not marked throwable but Image/IO did this. You can temporary add a `@try` and `@catch` to avoid this.

<img width="269" alt="2017-11-01 10 58 35" src="https://user-images.githubusercontent.com/6919743/32258100-aba6d518-be86-11e7-8eaf-a2aa69dac66b.png">

**Comment by dreampiggy** [comment]
Dumplicated for #943. This is a debug only exception when you set `All Exception: __cxa_throw in C++`. Image/IO will handler this exception and will not cause any problem. You can unmark `__cxa_throw` and keep `objc_exception` when you debug. 

This is also happend during AVPlayer framework, just ignore this one
