### ISSUE TITLE
shouldDecompressImages set to false causing increase in ImageIO_PNG_Data

### ISSUE THREAD

**Issue by terasupernova** [rs/SDWebImage#2112]
Hello, everybody.
I'm using SDWebImage to display pictures in a UICollectionView.
When I inspect my app, I got a huge amount of memory used - raster data
So i set the 
`SDImageCache.shared().config.shouldCacheImagesInMemory = false
        SDImageCache.shared().config.shouldDecompressImages = false
        SDWebImageDownloader.shared().shouldDecompressImages = false`
The raster data reduce a lot, but my ImageIO_PNG_Data and ImageIO_jpeg_Data increase. 
Any ideas how to decrease the memory used of ImageIO_PNG_Data and  ImageIO_PNG_Data?
Thanks in advance.

Before
![screen shot 2017-11-23 at 5 52 12 pm](https://user-images.githubusercontent.com/8252838/33167250-ef14f886-d077-11e7-9f95-f495130e3e6c.png)

After 
![screen shot 2017-11-23 at 5 52 42 pm](https://user-images.githubusercontent.com/8252838/33167263-fa26fb70-d077-11e7-81ee-cf516119cdbe.png)

**Comment by dreampiggy** [comment]
There seems no way to avoid this.

For image format, which is also called image container format, is a compressed algorithm to encode image bitmap data. So when you load a image into memory, it should be decompressed and increase memory.

The `ImageIO_PNG_Data` and `ImageIO_jpeg_Data` is memory used by Image/IO framework and used by `CGImage`, which is a samll part to allow their decoder to work. But this can not directly used for `UIImageView` because CALayer need rasterized bitmap. So it need another memory to save that. It's the `CG raster data`.

SD's `shouldDecompressImages` is used to directlly decompress `CGImage` create by Image/IO to rasterized bitmap in advance(before you set `UIImage` to `UIImageView` and let CALayer render). It can increase frame rate because the decompress procedure is under background queue. But this will increase memory because rasterized bitmap is larger that Image/IO's used memory.

If you really care about memory usage, try to reduce image size(this is a bad way in some cases). You can do this from custom coder from SD 4.2

**Comment by terasupernova** [comment]
Thanks @dreampiggy, will try that :)
