### ISSUE TITLE
3.8.1 无法加载https资源图片

### ISSUE THREAD

**Issue by SY13153288076** [rs/SDWebImage#2122]
### New Issue Checklist

* [ ] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [ ] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [ ] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name            ios /
 Platform Version         10.0
 SDWebImage Version      3.8.1
 Integration Method      sd_setImageWithURL:url placeholderImage: options:SDWebImageAllowInvalidSSLCertificates
 Xcode Version            Xcode 8.1

### Issue Description and Steps

3.8.1 版本无法加载https资源图片,我退回到3.7.6版本的时候,又可以加载了.url地址@"https://h5.zhsiwei.com/V6-banner.jpg";

**Comment by dreampiggy** [comment]
3.8.x use NSURLSession instead of NSURLConnection. Your url seems add a untrusted SSL certificate. So you should try to handle that either enable `SDWebImageAllowInvalidSSLCertificates` or prodive custom SSL trust chain in `-[URLSession didReceiveChallenge:]`(Maybe you can currently do this through custom `SDWebImageDownloadOperation`)
