### ISSUE TITLE
How to decode animated WebP only first frame

### ISSUE THREAD

**Issue by Silence-GitHub** [rs/SDWebImage#2128]
When creating animated WebP with image data, all image frames will be decoded. It may cost much memory. The WebP UIImage animation duration for each frame may be wrong. I need to use YYAnimatedImageView to display WebP, and image data is needed to create YYImage. I use SDWebImage to load image data. So, I should not decode all WebP image frames. This situation is like GIF and FLAnimatedImage. We load GIF data and decode only first frame. How can I get image data and decode animated WebP only first frame ?

**Comment by dreampiggy** [comment]
There is some reason related to this questio, and I want spend some more time to talk about it.

> The WebP UIImage animation duration for each frame may be wrong

SDWebImage from 4.1 fix the duration per frame bug in animated WebP. It use a calculation of GCD to each frame duration and repeat the `UIImage` several times and finally call `[UIImage animatedImageWithImages:duration:]`. See #1951 and #1952.

But to tell the truth, `[UIImage animatedImageWithImages:duration:]` method will keep all the instance into memory, this is suitable for small animted WebP images and have a really fast render performance. But when you decide to show many big animted WebP images, this may cause OOM.

YYImage, use another way to solve this issue. It create a UIImage subclass `YYImage` class, keep the image source into that instance. For Image/IO supported format, is `CGImageSource`. For WebP, is `WebPDemuxer`. And it also have one specify animted imageView `YYAnimatedImageView`. When you set a `UIImage` instance on it, it just show as normal `UIImageView`. But when you set a `YYImage` on it, it will use a `CADisplay` to render your image for each frame. It firstly decode, and then produce a `CGImage` through the inner image source when current frame's duration time reached.

This can keep that only single frame instance alive at the sametime. So can reduce large memory usage for animted images. But it also cost extra CPU usage, because of that implementation, it need to re-decoding each frame everytime even you just leave your App without doing anything. This is a time-space balance.

**Comment by dreampiggy** [comment]
So, why SDWebImage currently use this implementation ? This may because of that SDWebImage historical design usage. It forcus on **Simple** and **Category-friendly** use case. So we do not need to including extra `UIImageView` subclass to showing the animated images.

But why we now have that `FLAnimatedImageView` ? This is because a huge refactory during 4.0 in #1575. We include `FLAnimatedImage` to support GIF rendering. Sadly, `FLAnimatedImage` does not do something like `YYImage`, it does not subclass from `UIImage`. And it just support GIF, but not general enough to support other animted image format such as APNG, WebP.

Maybe we can do another big refactor, to provide the same way like YYImage to support big animated images rendering. Such as create an new class `SDAnimatedImageView` and `SDImage` But this may cause a lot of time and we need contributer to support this feature. If someone need this, we can add a feature-request to future milestone. 👍

**Comment by dreampiggy** [comment]
And also, for your last question:

> How can I get image data and decode animated WebP only first frame ?

SDWebImage 4.2 introduece coder plugin. Which you can implement your own image decoder and encoder, see https://github.com/rs/SDWebImage/tree/4.2.0.

So for your case, you can just write a coder to produce a `UIImage` subclass instance like YYImage. Which just contains the first frame and keep that `WebPDemuxer` inside to decode other frames when you need.

In fact, since all our image decoding/encoding process exposed as custom coders. So you can even write a wrapper to use SDWebImage instead of YYWebImage to play with YYImage. (Sounds interesting ?). You just need to write a new category for `YYAnimatedImageView`, write a custom coder to directly call `YYImageCoder` methods, then combine them up :)

**Comment by dreampiggy** [comment]
If you're still interested in this issue, try to see #2140. We introduce a `YYAnimatedImageView` like new image view `SDAnimatedImgeView` and `SDAnimatedImage`, which also take benefit from our custom coder plugins and integrate with all the lib(cache, manager, downloader, category). You can have choice to use normal UIImageView+UIAnimtedImage(small images, low CPU & high memory) or SDAnimatedImageView+SDAnimatedImage(big images, high CPU & low memory) by the same interface.

**Comment by dreampiggy** [comment]
We add a `SDWebImageDecodeFirstFrameOnly` options in 5.x branch. Currently our build-in coder always try to decode animated images if the original data is a animated format. You can try using `image.images.firstObject` to grab the first frame only. But in 4.x it seems that we can not break the current API to add a extra information to indicate that the custom coder `SHOULD decode first frame only`. :)

For more information, see #2140

**Comment by Silence-GitHub** [comment]
Thank you! I solved the problem by implementing custom image coder.

**Comment by dreampiggy** [comment]
:) I'll create a `YYImage+WebCache` CococaPods with SDWebImage 5.x dependency. You can directlly use `YYAnimatedImageView+WebCache` to load anything with SDWebImage without YYWebCache. All the API looks the same as `UIImageView+WebCache`

This is done by mark `YYImage` to adopt `SDAnimatedImage` protocol and provide a custom class. This is how our `SDAnimatedImageView` works. And you can even feed `YYImage` to `SDAnimatedImageView`. Sounds good for you.

**Comment by dreampiggy** [comment]
#2140 Merged. If who are interested in that New Animated Image Solution for iOS & macOS with custom coder support. You can try 5.x branch or wait for 5.0.0-beta release
