### ISSUE TITLE
Images can not load.

### ISSUE THREAD

**Issue by AaronV5V5** [rs/SDWebImage#2133]
I have send the image to Aliyun server, but some images can be showed, the others can not, here are two examples, http://yomo.oss-cn-hangzhou.aliyuncs.com/image/77FD2D3F-B37C-4BAA-A718-98F27C385A9E, http://yomo.oss-cn-hangzhou.aliyuncs.com/image/E322F2C7-1214-4632-A686-33B8EF3E9403

**Comment by mythodeia** [comment]
@AaronV5V5 are you sure the above links are images?

**Comment by dreampiggy** [comment]
The first one is a HEIC image(file signature `6674 7970 6865` - `ftypheic`)
The second one is a PNG image(file signature `8950 4e47 0d0a 1a0a` - `‰PNG....`)

So, for HEIC images, it needs iOS 11 on real device (not simulator) or macOS 10.13, check your system requirement or customer firmware version.

The second one should be loaded, you can try again and better provide more information with some screenshot or console log.

**Comment by AaronV5V5** [comment]
when can SDWebImage support HEIC images? Or I can show HEIC images? Thank you.

**Comment by dreampiggy** [comment]
For iOS 11 and macOS 10.13 above, all HEIC images is natively supported by Apple's framework and you do not need do anything. You can use `NSData+ImageContentType` to check the image foramt.

If you still and really strongly hope to support HEIC images on lower firmware version, you need to write your own HEIC image decoder. Because it need extra library(such as [FFmpeg](https://github.com/FFmpeg/FFmpeg), [openHEVC]https://github.com/OpenHEVC/openHEVC because HEIC image based on HEVC video codec format), so we do not provide HEIF decoder through our framework, you can write your own HEIF coder and embed with our custom coder plugin.

To learn how to use SDWebImage through custom coder plugin, see : https://github.com/rs/SDWebImage/releases/tag/4.2.0 and the documents in `SDWebImageCoder`. You can also learn some demo such as [SDWebImageBPGCoder](https://github.com/SDWebImage/SDWebImageBPGCoder).

**Comment by dreampiggy** [comment]
To say, it's better to write a wiki or some detailed documents to show the custom coder plugins. But it need a lot of time. Maybe I need to provide one in my extra time :P

**Comment by AaronV5V5** [comment]
I am glad to receive you messages quickly, thank you all right

**Comment by dreampiggy** [comment]
HEIC support on lower firmware is a huge work, and it need expert on multimedia decoding. It's far away from common iOS development, so it's better to let expert person to do their work. (Our company's multimedia team write a cross-platform HEIC decoder from the scratch and it takes nearly 2 months)

**Comment by AaronV5V5** [comment]
So I have to give up to go this way and I will transform HEIC to jpg or png when users submit images, how dou think about it? Thank you

**Comment by dreampiggy** [comment]
@AaronV5V5 It's a better solution for this. When you use image picker to let user grab images, you should try to encode it to common image format such as PNG, JPEG and even WebP(now we support WebP encoding :D). Then upload to the server. Or you can ask your server to do a post-transform when the image format is not supported by client.(FFmpeg's command line tools can do this work).

My company now use HEIC only for rare case because it's not really common and our decoder is in experience. We upload the user provided image through WebP. Hope this can also be helpful for you.

**Comment by AaronV5V5** [comment]
Thank you.But my company upload images to aliyun server, so only the client do this work.
