### ISSUE TITLE
Crash in SDWebImageDownloaderOperation.m line 144

### ISSUE THREAD

**Issue by DarkoDamjanovic** [rs/SDWebImage#2156]
I experience a crash in SDWebImageDownloaderOperation.m line 144:

http://crashes.to/s/3a87aad8f79

This is the line in code:

`NSCachedURLResponse *cachedResponse = [[NSURLCache sharedURLCache] cachedResponseForRequest:self.request];`

I assume that the access to the shared NSURLCache has to be synchronized here.

 Platform Name           | iOS
 Platform Version        | 9.0, 10.0
 SDWebImage Version      | - SDWebImage/Core (4.2.2) 
 Integration Method      | cocoapods
 Xcode Version           | Xcode 9.2
 Repro rate              | rare

Thanks.

**Comment by dreampiggy** [comment]
😞 Previously, there is a crash related to the `NSURLCache` because we store the image data with the request during SD4.0~SD.4.1.1. See #1623.

So we place the `cachedResponseForRequest` call before any request start to avoid URLSession internal call something related to the cache and cause thread-safe problem. However, your crash seeems that this affort still contains some race condition. How many ratio does this crash happend ? (To see if the ratio can smaller than the previous solution)

Apple docs says:
> Although NSURLCache instance methods can safely be called from multiple execution contexts at the same time, be aware that methods like cachedResponseForRequest: and storeCachedResponse:forRequest: have an unavoidable race condition when attempting to read or write responses for the same request.

**Comment by dreampiggy** [comment]
If we have no choice, maybe we should add a global lock(!) to ensure all the acess to `[NSURLCache sharedURLCache]` are synchonized but not just operation instance itself. This will dramatically impact the performance. Maybe we should take more concern.

**Comment by DarkoDamjanovic** [comment]
I can't find ratio informations in Crashlytics. But it's rare, so it's not severe.

**Comment by dreampiggy** [comment]
@DarkoDamjanovic It should be a really small ratio. This acess to `[NSURLCache sharedURLCache]` is only happened in `start` method. This means that the thread-safe problem is not caused by `SDWebImageDownloladerOperation` itself. But it's because any other call in our library (and even not our library).

For example, your `viewDidLoad` call `[[NSURLCache sharedURLCache] cachedResponseForRequest:self.request];` with the same request(Acutally, with the same URL because I decompiled the CFNetwork and see it just use a global std::map to store memory cache).
Then this may cause the crash, really `unavoidable`.

For now, our library would not download the same URL again because of we reuse the operation. So  this should be another call outside `SDWebImageDownloladerOperation`
See :https://github.com/rs/SDWebImage/blob/master/SDWebImage/SDWebImageDownloader.m#L242-L258

**Comment by dreampiggy** [comment]
@DarkoDamjanovic Could you please more information about how you use SDWebImage ?
For example: 
+ did you use self alloced instance other than shared manager, shared downloader ?
+ did you use custom `SDWebImageDownloaderOperationInterface` class ?
+ did you use SDWebImageDownloaderOperation without downloader(which means use the unowned session) ?

Maybe these information can help me to identify the acutal cause of the issue.

**Comment by DarkoDamjanovic** [comment]
Why don't you just synchronize the access on this one line? If `sharedURLCache` is a global std::map then (as you already said) other libraries could just **set** another `sharedURLCache` exactly at the moment when you want to access it. As this is not an atomic operation the `sharedURLCache` could be nil exactly at that time. 

I only use:

`SDWebImageManager.shared().loadImage`

And the extension methods on `UIImage`.

**Comment by dreampiggy** [comment]
See #2157

**Comment by DarkoDamjanovic** [comment]
I see. Well, global shared mutable state.. the root of all multithreading evil. How about using just your own instance of an NSURLCache instead of the shared one?

**Comment by dreampiggy** [comment]
@DarkoDamjanovic This may be a good advice. Since `NSURLSessionConfiguration` contains the `URLCache` property. Maybe we can then bind each `SDWebImageDownloader` a non-shared `NSURLCache`.

This may help this issue, but this may also has a potential disadvantage. If user create their own `SDWebImageDownloader`, they can not get the already cached response from other downloader instance and will re-download. But this looks acceptable, I'll try one and build my applications for local test.

**Comment by dreampiggy** [comment]
I think we should wait to see if there are further crash report. I think this may be a bug on iOS 9's CFNetwork framework. See the anaylsis in #1623

If you can sure iOS 10 and above also contains this crash, fell free can then reopen this. Thanks :)
