### ISSUE TITLE
Extremely high memory usage, NSCollectionView

### ISSUE THREAD

**Issue by mohacs** [rs/SDWebImage#2176]
Platform Name: macOS
Platform Version: 10.13.2 (17C205)
SDWebImage Version: 4.2.3
Integration Method: Cocoapods
Xcode Version: 9.2 (9C40b)
Language: Swift 4

Hi guys, 

I am using SDWebImage for download/show images to NSImageView inside NSCollectionView (flow layout) cells. images are located in AWS s3, image's resolutions are 1280 × 853 (standard for all images) and file sizes varies between 110-190 kbyte. 
using HTTP instead of HTTPS, I can confirm images are cached alright because I do not see network activity after first pass, all images comes from cache. 
In the collection view there are 200 images max at the same time. 

When I am creating NSCollectionViewItems and most of the objects I am using "unowned" / "weak" declarations, in deinit I am setting all possible objects to nil. I can tell there is no related leak when I check it with Instruments. There are some leaks but they comes from standard swift libraries and 200-300k in total. 

Usage is pretty standard:

`cell.imageView.sd_setImage(with: img_url, completed: nil)`

Following config values set to false:

```
SDImageCache.shared().config.shouldDecompressImages
SDWebImageDownloader.shared().shouldDecompressImages
```

in a loop every 30 seconds calling 

`SDImageCache.shared().clearMemory()`

After couple of times scrolled down then up memory usage hits to 1 - 1.5 GB in average for per tab. If I keep scrolling it climbs up... Even after I destroyed the window controller (cmd + w), it is not releasing memory. I can see deinit called. 

To be sure is it my code or the library I added Kingfisher library in to my project, memory usage did not go up more than 600Mb for per tab. And released afterwards.

Last 4 days, I read every line in issues about high memory usage, tried everything in my knowledge but I stuck. I believe something wrong with the library when use it with macOS because there is no issue on IOS for same cases. 

Actually i am writing new version of an old app of mine from 2013, it is using SDWebImage as well and it's memory usage average is around 300-400Mb for per tab. 

Any help or suggestions would be appreciated. I would like to post my project but it is huge. 

I prepared a new project for test, please see attached zip file. If you scroll down and up couple of times you will see the extreme memory usage.

Cheers.

[SDWebImageTest.zip](https://github.com/rs/SDWebImage/files/1629841/SDWebImageTest.zip)
Extremly

**Comment by dreampiggy** [comment]
Thanks for your reply. I'm trying to figure out the memory usage issue. It seems that we may have some issue in history about macOS. We'll try to fix them and make our library work for as may platform as we can.

**Comment by dreampiggy** [comment]
Too tell the truth, I advise all the user enable the `shouldDecompressImage`, this is not what that comments means and are misunderstanding.

This options means that we will try to draw the ImageRef on the context in the background queue, and then use this image. This can avoid UIKit/AppKit to decode the image in the main queue after you set the image to imageView. This can dramatically increase the frame rate. And the memory usage it's actually equal because UIKit/AppKit decode the image in main queue also need to hold the memory, we just make this in advanced and dispatch it on a background queue to avoid blocking it.

**Comment by dreampiggy** [comment]
It seems that we have some memory leak issue in `-[SDWebImageManager runningOperations]` when all the image was cached, this `NSMutableArray` should be empty. But by running your demo, I found that the array is not empty. There must be some of bug. I think I should review that logic again and find a better way to avoid this.

To say, I think the `cancelBlock`and `weak-strong` to break retain cycle is really dangerous. :)

**Comment by dreampiggy** [comment]
@mohacs Could you please try to use that PR to test if this issue still exist ?

```ruby
pod 'SDWebImage', :git => 'git@github.com:rs/SDWebImage.git', :branch => 'fix_running_operation_leak'
```

**Comment by mohacs** [comment]
@dreampiggy hi, when I do pod install, here is the result and thank you so much for looking into this. 

Pre-downloading: `SDWebImage` from `git@github.com:rs/SDWebImage.git`, branch `fix_running_operation_leak`

[!] Error installing SDWebImage
[!] Failed to download 'SDWebImage'.

Cheers,
-mohac.

**Comment by dreampiggy** [comment]
@mohacs My mistake, use my PR's fork repo :)

```ruby
pod 'SDWebImage', :git => 'git@github.com:dreampiggy/SDWebImage.git', :branch => 'fix_running_operation_leak'
```

**Comment by mohacs** [comment]
@dreampiggy changed in to this and i was able to download it. 
pod 'SDWebImage', :git => 'https://github.com/dreampiggy/SDWebImage.git', :branch => 'fix_running_operation_leak'

I have deleted everything inside the derivedData folder include module caches etc and built project with the updated library. 
I am sorry, no difference. Still memory consumption is around 1 - 1.5 GB per tab (same project), unless set 

`SDImageCache.shared().config.shouldCacheImagesInMemory = false`

When it is set to false, memory usage is around 800-900 MB and this time when I dismiss the window controller it releases 100-150 Mb memory. 

If there anything else I can check, please advise?

Cheers,
-mohac.

**Comment by dreampiggy** [comment]
Can you use Instuments and use `Allocations` to check what instance contains the memory. I assume that it's `SDImageCache`'s memory `NSCache` because macOS unlike iOS, do not have a `UIApplicationDidReceiveMemoryWarningNotification` to clear the cache when memory warning. You need to clear it youself or use the `maxMemoryCost` in `SDImageCacheConfig` to limit the max cache size.

**Comment by mohacs** [comment]
hi @dreampiggy, sorry for being pesty. All images are good old jpegs, there is no WebP, gif or png images. 

Calling this function every 5 seconds. 

```
    @objc func clearnSDWebImageCache() {
       SDImageCache.shared().clearMemory()
       print(SDImageCache.shared().getSize())
    }
```

Something catchy here. If I comment out SDImageCache.shared().clearMemory() line, getSize() result is alway 21923394. 
shouldCacheImagesInMemory = false or true OR maxMemoryCost = 100 * 1024 * 1024
doesn't matter, it always print 21923394. Is it normal?

Tonight, I will check "Allocations" and let you know.

Cheers,
-mohac.

**Comment by mohacs** [comment]
hi @dreampiggy, I do not see any problem on allocations. As I can see only the problem right now 

SDImageCache.shared().clearMemory()

is not working for me, SDImageCache.shared().getSize() printing same value before and after 
SDImageCache.shared().clearMemory() called.

**Comment by dreampiggy** [comment]
`SDImageCache.shared().getSize()` return the disk cache size but not memory usage. So only if you call `clearDiskOnCompletion` will remove the disk cache.

You say `I do not see any problem on allocations`. So...What was that acutally take your memory ? Isn't UIImage instace ?

I think maybe UIKit/AppKit's decoded data(`CG Raster Data`) stored not in UIImage or CGImage instance level, it managed on the view(acutally layer or context) level. So if the view instance dealloc, the decoded rasterized data dealloc. Even the `NSImage` instance is alive and kepted in the `SDImageCache`, the consumed memory is lower because it's a undecompressed format.

If you specify the `shouldDecompress`, we will create a new image by rendering it on the context, this may force the decoded data stored in CGImage level, so that this will cause more memory (The benefit is frame rate), and even the view instance dealloc, the decoded data store in CGImage instance will not dealloc. This may explain the phenomenon you faced.

Previously I'm aware of this difference between `decompress`, this looks like a of trade-off between memory and efficiency. I will check the this behavior again with some demo.

**Comment by mohacs** [comment]
@dreampiggy I noticed two different problems on my code. Actually one of them is not my mistake but Apple's. If you use xib for NSCollectionViewItem, it is leaking like a hell. I deleted xib and created everything with code. Now there is no leak. 

The second problem I mention about earlier was "not releasing memory" even after NSWindowController closed. it was because of a Timer I am using to invoke SDImageCache.shared().clearMemory(). 

Right now on the Instrument there is no leak however high memory problem still here. While browsing up and down in to collection view it hits to 1-1.5 GB. 

![screen shot 2018-01-17 at 4 13 43 am](https://user-images.githubusercontent.com/1199239/35020450-2ae2913a-fb3d-11e7-9d40-e9faa9e57850.jpg)

Today it is kinda late but for sure tomorrow I will do the test with Kingfisher and let you know the results. 

Thank you,
Cheers,
-mohac.

**Comment by mohacs** [comment]
@dreampiggy sorry for delay, i got cold, can't working right now. I will let you know asap once I get up

**Comment by dreampiggy** [comment]
After some research, it seems that the Core Animation on iOS follow the behavior I describe. They cache the decoded JPEG data into Core Animation's zone instead of CGImage itself if you rendering it without `decompress`.

However, on macOS, it seems that Core Animation does not do this, the decoded JPEG data stored in `bitmapRep`

**Comment by mohacs** [comment]
@dreampiggy my apologies for the delay, just today i could hold myself together.  
Re "Kingfisher and enabling decompress", after I set decompress by using .backgroundDecode, UI is barely moving (NSCollectionview) but I did not observe higher memory usage?

As I mentioned earlier, after I fixed the leaks and strong reference problem, right now when I dismiss the window controller it releases all the memory it is using, however while using it same high usage stands. 

Since there is no leak on SDWebImage or somewhere else, after your detailed explanations we could say this is how NSCache handles the images on macOS and go on? :) 

Cheers

**Comment by dreampiggy** [comment]
@mohacs This is actually the difference between `UIImageView` and `NSImageView` handler for the CGImage. `UIImageView` store the internal CG raster data to their layer but `NSImageView` does not and store the internal CG raster data to `CGImage` level. So althrough both of two the `UIImage` or `NSImage` instance is still alive if you do not clear cache, the memory usage is different.
