### ISSUE TITLE
PlaceholderImage doesn't work with animated Gifs.

### ISSUE THREAD

**Issue by rpstro02** [rs/SDWebImage#2217]
When loading a remote image with sd_setImage, the placeholder image doesn't work with animated gifs.  It won't accept FLAnimatedImage (since FLAnimatedImage is not a UIImage subclass) and won't animate a UIImage that is an animated GIF.

**Comment by dreampiggy** [comment]
You can pass a `UIAnimatedImage` created by `-[UIImage animatedImageWithImages:duration:]`. Which can be shown correctlly.

However, since `FLAnimatedImage` is not a `UIImage` subclass, you can not pass one to do placeholder. This will be fixed into 5.x because we drop out that `FLAnimatedImage` subspec and introduce own `SDAnimatedImage`, which is a `UIImage` subclass.

For now, just use some other way like that `UIAnimatedImage` or set the placeholder yourself before calling `sd_setImageWithURL:` with `SDWebImageDelayPlaceholder` 😅

**Comment by rpstro02** [comment]
`UIImage.sd_animatedGIF(with: animatedPlaceholderData)`

This works.  Thank you for the reply.

**Comment by dreampiggy** [comment]
@rpstro02 Maybe a better way. We can expose the associate object in `FLAnimatedImage+WebCache`. Then you can create a new `FLAnimatedImage`, bind this to your `UIImage` placeholder and call the `sd_setImageWithURL:`.

In 4.3.0 we introduce this to fix some issue and "store" the `FLAnimatedImage` into memory cache. But it's read-only because at that time I think it's should be a advacend feature and user should avoid touching this. Now I think it's time to open the ability to set that property.
