### ISSUE TITLE
(Webp) loopCompletionBlock has never called when using with FLAnimatedImageView.sd_setImage(with: URL(string:

### ISSUE THREAD

**Issue by bembem1011** [rs/SDWebImage#2233]
I need to know when webp Image, which is downloaded form internet, finished animation. However, the loopCompletionBlock has never be called

private let imgView = FLAnimatedImageView();
imgView .sd_setImage(with: URL(string: urlLink));

imgView .loopCompletionBlock = { count in
dbLog("test count") // not be called ?
}

PS: I downloaded images before
let prefetcher = SDWebImagePrefetcher.init()
      prefetcher.prefetchURLs(urlStrs.flatMap { return $0 }, progress: nil, completed: nil)

**Comment by dreampiggy** [comment]
WebP is just a `UIAnimatedImage` when using with `FLAnimatedImageView`. So they does not do anything to loop in their own implementation. So current there is no way to KVO a loop finished. You can specify 1 for `animatedLoopCount` and KVO `animating` property on `UIImaegView/FLAnimatedImageView`, there is the only way for build-in property.

In 5.x we have `SDAnimatedImageView` and support a specify `SDAnimatedImage` which is a subclass of `UIImage/NSImage` and support custom coder, the animated image can be GIF, APNG, Animated WebP images. It supports you to KVO two property `currentLoopCount` and `animating`.

 This can solve these problem because it's written by ourself instead of buld-in imageView class from Apple.

**Comment by bembem1011** [comment]
Thanks @dreampiggy,

I set 

`imgView.animationRepeatCount = 1`

However, my webp animation doesn't stop, it loops forever :(. May you help me to give the example for using KVO to watch `animating` property on UIImageView ? :( Thanks very much Y_Y

Therefore, When is the release of branch 5.x?

**Comment by dreampiggy** [comment]
@bembem1011 That's Apple's API design issue.
If you use a `UIImage` create by `-[UIImage animatedImageWithImages:duration:]`(This acutall class is `UIAnimatedImage`, no repeat). Then set this `UIAnimatedImage` to `UIImageView`. It loops forever.

If you want to control the loop count. You should write this code instead:

```objective-c
self.imageView.image = image.images.firstObject; // This will cause the animation stop at the first frame. You can also use lastObject if you need to stop at last frame.
self.imageView.animationRepeatCount = image.sd_imageLoopCount; // Sepcify animation loop count
self.imageView.animationDuration = image.duration;
self.imageView.animationImages = image.images;
[self.imageView startAnimating];
```

Then, add KVO on `self.imageView.animating`, you will get KVO called after that loop count finished.

**Comment by bembem1011** [comment]
Hi @dreampiggy 

Will this issue be handled in branch 5.x's SDAnimatedImageView ? May you tell me the 5.x's final release time ?

Thanks very much :(

**Comment by dreampiggy** [comment]
The release date maybe April, but maybe there is a beta version first(5.0-beta), and we should fix some bugs or wait for any other important API-break changes.

The 5.x may not break something like 4.x. For the core API like `sd_setImageWithURL`, nothing changed. So feel free to update :)

The biggest changes are mostlly on advanced feature like custom coder(The protocol may change a bit), custom transformer(Use a `id<SDWebImageTransformer` instead of delegate method), custom cache(No big API change).It all here in [5.x milestone](https://github.com/rs/SDWebImage/milestone/15)

**Comment by bembem1011** [comment]
Thanks very much @dreampiggy
