### ISSUE TITLE
property with 'retain (or strong)' attribute must be of object type

### ISSUE THREAD

**Issue by archerLj** [rs/SDWebImage#2234]
I used SDWebImage in my private repository, and this is the code : 
```
  s.dependency "SDWebImage"
```
in my podspec file, And when i push the podspec file,  it give me the following error:
```
/var/folders/02/c9zfh1097t500m37ts3v5mrm0000gn/T/CocoaPods/Lint/Pods/SDWebImage/SDWebImage/SDWebImagePrefetcher.h:64:1: error: property with 'retain (or strong)' attribute must be of object type
@property (strong, nonatomic, nonnull) dispatch_queue_t prefetcherQueue;
```

**Comment by dreampiggy** [comment]
You're not using ARC and dispatch object for Objective-C. Check you Xcode version and compiler config. 

Dispatch Object in Objective-C is a `NSObject<OS_dispatch_queue_t>`, So it should use as `strong` since it's a object but not value type.

You can check whether your compiler options enable `OS_OBJECT_HAVE_OBJC_SUPPORT` or `OS_OBJECT_USE_OBJC`

**Comment by loveNoodles** [comment]
I encountered the same question . 
My Xcode is 10.0 . platform :ios,  '10.0' .Both OS_OBJECT_HAVE_OBJC_SUPPORT and OS_OBJECT_USE_OBJC are defined in usr/include->os->object.h .  
But l still got this error ! Any help is appreciated .
