### ISSUE TITLE
Why not store the decoded webp image ?

### ISSUE THREAD

**Issue by bembem1011** [rs/SDWebImage#2236]
After using sdwebimage to work with webp image and reading code in current version, I see sdbwebimage save the downloaded data instead of saving the decoded webp image to disk. Why not supporting for saving decoded webp image ? Because after reading the downloaded webp data which stored at disk, the framework will parse downloaded data to UIImage. Doing parsing large data will cost time. I think we should support for saving decoded data to disk in next version

**Comment by dreampiggy** [comment]
@bembem1011 We can't simply  `store the decoded webp image` like you say, it contains many bad effect.

When you decide to `store the decoded webp image`, actually you means to **ENCODE the UIImage again and store the data**. Right ? However, since many of our feature may relay on the original image data(For example, `scale down` or our `transformer` feature in 5.x)

And there are also a question, show this behavior only applied for WebP images ? What about GIF, APNG, BPG and so many other image format ? (We support custom coder to enhance your feature)

So, maybe currently we could not change this behavior. If you're really considered to use this behavior, you can try using [Custom Download Operation](https://github.com/rs/SDWebImage/wiki/Advanced-Usage#custom-download-operation-40)

**Comment by bembem1011** [comment]
@dreampiggy Thanks for your answer, but using "Custom Download Operation" seems doesn't match with my idea. I see SDWebImageManager has method 
`- (id <SDWebImageOperation>)loadImageWithURL:(nullable NSURL *)url
                                     options:(SDWebImageOptions)options
                                    progress:(nullable SDWebImageDownloaderProgressBlock)progressBlock
                                   completed:(nullable SDInternalCompletionBlock)completedBlock {`

I see below code in downloaded completion block
`if (downloadedImage && finished) {
                            [self.imageCache storeImage:downloadedImage imageData:downloadedData forKey:key toDisk:cacheOnDisk completion:nil];
                        }`

May I extend SDImageCache to store the "downloadedImage" instead of storing "downloadedData" ? Is it the right solution and does it will make any bad performance for webp Image ?

**Comment by dreampiggy** [comment]
@bembem1011. Actually, I means you can just return the `encode from UIImage to data` in `SDWebImageDownloadOperation`'s completionBlock instead of the downloaded data. So then the manager will use this `NSData` instead.

Actually this maybe a bad idea in some cases when you may need the original data from your server but not the one you encoded again from a decoded image. Another way it to use `completionBlock` and store the NSData by your own, so you don't need to custom download operation.

Maybe there is other better way to solve this problem such as provding a extra delegate method or layer to allow user to return a `modified version NSData` before acually store it to disk. But currently in 4.x it seems we can not change to much for this. I'll mark this as a feature request to see if any better idea is provided.

**Comment by bembem1011** [comment]
@dreampiggy  Thanks for you answer, I agree with you about providing 

> extra abstract layer to allow user to return a modified version NSData before acually store it to disk(Like Kingfisher's CacheSerializer

How about providing it in next version 5.x in April ?

**Comment by dreampiggy** [comment]
@bembem1011 See #2245. If you are facing the issue of WebP decoding speed from disk cache. You can considerate to encode the image to another format such like JPEG or PNG when storing to disk cache.

**Comment by bembem1011** [comment]
@dreampiggy Thx :D:D:D:D

**Comment by bembem1011** [comment]
@dreampiggy  once more question ? why not support for using FLAnimatedImageView with webp image because some webp images are so large to decode which makes app waiting a long time to construct UIImageView.animationImages

**Comment by dreampiggy** [comment]
@bembem1011 FLAnimatedImage is currently hardcoded to play GIF only. In 5.x we introduce a totally replacement for FLAnimatedImage, and we also allow you to use the original way(`UIAnimatedImage` from UIKit) way to play animated image.

To learn more, see #2140

**Comment by bembem1011** [comment]
@dreampiggy  Thank you :)

**Comment by dreampiggy** [comment]
#2245 Merged and 4.3.3 released
