### ISSUE TITLE
Do not force decode GIFs using sd_imageFormatForImageData

### ISSUE THREAD

**Issue by OneSman7** [rs/SDWebImage#2253]
### New Issue Checklist

- [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
- [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
- [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        | 11.0
 SDWebImage Version      | 4.3.3
 Integration Method      | cocoapods
 Xcode Version           | Xcode 9
 Repro rate              | all the time (100%)
 Repro with our demo prj | no
 Demo project link       | no

### Issue Description and Steps

Hello! I am using SDWebImage to download and cache GIF animations. I use FLAAnimatedImage, but do not use your integration to decrease memory usage.
When I get the first GIF frame from the memory cache I check its UTI

`image.cgImage?.utType == kUTTypeGIF`

If the type is gif and I do not have image data I simply refetch the image, but with SDWebImageQueryDataWhenInMemory option. Thus GIF images are always queried from the disk.

But I found code in SDWebImageDownloaderOperation that decompresses downloaded images and thus destroys type information. There is code that tries to skip decompressing for animations

`BOOL shouldDecode = YES;
                        // Do not force decoding animated GIFs and WebPs
                        if (image.images) {
                            shouldDecode = NO;
                        } else {
#ifdef SD_WEBP
                            SDImageFormat imageFormat = [NSData sd_imageFormatForImageData:imageData];
                            if (imageFormat == SDImageFormatWebP) {
                                shouldDecode = NO;
                            }
#endif
                        }`

But for GIFs it uses checking `image.images` array which is almost always nil.
Therefore I propose checking image format from data like in WEBP case with method sd_imageFormatForImageData. Like so

`                      BOOL shouldDecode = YES;
                        // Do not force decoding animated GIFs and WebPs
                        SDImageFormat imageFormat = [NSData sd_imageFormatForImageData:imageData];
                        if (imageFormat == SDImageFormatGIF) {
                            shouldDecode = NO;
                        } else {
#ifdef SD_WEBP
                            if (imageFormat == SDImageFormatWebP) {
                                shouldDecode = NO;
                            }
#endif
                        }`

Would not this be a good improvement?

Thanks!

**Comment by dreampiggy** [comment]
Since you use `FLAAnimatedImage`, but without our `FLAnimatedImageView+WebCache` ?

If you need the extra information keep in `UIImage` or `CGImage` class itself without that decompress, just set the `shouldDecompressImage` to NO.

If you still want to keep the decompress feature, you can consider using the advanced API in `UIView+WebCache`, the `sd_internalSetImage(with:placeholderImage:options:operationKey:setImageBlock:progress:completed`, which provide a `NSData` arg to allow you grab the data. For normal `UIImageView`, you can just pass `setImageBlock` and `operationKey` to nil.

If all of these can solve your problem, maybe you can consider to custom download operation by subclassing `SDWebImageDownloadOperation`(Maybe you need Objective-C) and modify that decompress logic. This logic will be changed in 5.x, but in 4.x, we maybe not change this too much.

To say, if you are using `FLAnimatedImageView` in 4.x, it's strongly recommend to use that `FLAnimatedImageView+WebCache`, or maybe you can create your own category by referencing the code there, because it solve some problem by a little tricky logic.

**Comment by OneSman7** [comment]
Yes, I do not use `FLAnimatedImageView+WebCache`
It indeed uses tricky logic that will solve the same problem, but by keeping whole GIF in memory. I prefer more disk operations to large memory footprint in my case.

You say that decompress logic will change in 5.x. Can you please tell what will be changed?
I came to an idea that I can design my own `SDWebImageCoder`, a subclass of `SDWebImageImageIOCoder` which can simply check what I need before calling `- (nullable UIImage *)decompressedImageWithImage:(nullable UIImage *)image data:(NSData * _Nullable * _Nonnull)data options:(nullable NSDictionary<NSString*, NSObject*>*)optionsDict;`.

Will decoder management logic change in 5.x?

**Comment by dreampiggy** [comment]
@OneSman7 I can reply  your question one by one.

#### `FLAnimatedImageView+WebCache` keeping whole GIF in memory:

This is not correct. This category just ignore the `UIImage` args itself from the completion block. It use a associate object binding `FLAnimatedImage` instance, so actually, there are only one `NSData`, one cover image from the decoder, and one cover image keeping in the memory. Since  cover image is consider to less memory consuming, so this extra cover image from decoder should not decrease the performance.

But there are one exception, since `one cover image from the decoder` is control by the user, and if you enable [GIF Coder](https://github.com/rs/SDWebImage/wiki/Advanced-Usage#gif-coder), the return image instance will actually be a `UIAnimatedImage` and consume more memory. If your application does not need any GIF rendering on normal `UIImageView`, consider to disable that GIF coder.

#### You say that decompress logic will change in 5.x. Can you please tell what will be changed?

Actually, the logic will be changed to just seperate the `image format decoding` and the `draw into bitmap` logic, currently one method `decompressedImageWithImage: data: options:` will be removed. For the draw into bitmap and scale down logic, we move the code into `SDWebImageCoderHelper`. For each `UIImage` which is already drawed on bitmap, there is a flag `sd_isDecoded` to mark it to avoid secondary process.

#### More information about animated image rendering on 5.x

In 5.x, we will drop the code and dependency on `FLAnimatedImage` this third-party library. We create the own solution from the scratch by introducing two class: `SDAnimatedImage : UIImage` and `SDAnimatedImageView : UIImageView`, which is both the subclass of UIKit class. Its design is based on the `CALayer` and `CADisplayLink`, supports custom coder, supports KVO on properties, supports macOS, and more. And we leave the control to you to use this class instead or `UIImageView` itself. You can even pass `SDAnimatedImage` on `UIImageView`, or `UIImage` on `SDAnimatedImageView` and it works.

For `FLAnimatedImageView+WebCache`, these code will move to another cocoapods project called `SDWebImage+FLAnimatedImage` to maintain. The official lib will focus on that animated image solution. To learn more, see #2140

**Comment by OneSman7** [comment]
Thank you for your rich explanation!

I guess I should consider spending some time refactoring when 5.x comes out. I looked through the PR and performance screenshots (against YYImage) look very promising. It would be great to see more performance comparisons against other libs when 5.x is released.

As for my current problem, the idea with custom coder worked. I subclassed `SDWebImageImageIOCoder` and in overridden methods made sure that data is checked for format and GIFs are not going through decompression. Thus UTI parameters stays intact.

I will be closing this issue since the problem is solved. Thank you again!
