### ISSUE TITLE
Duplicate Linker issues in project that also uses FLAnimatedImage

### ISSUE THREAD

**Issue by ketzusaka** [rs/SDWebImage#2279]
### New Issue Checklist

* [X] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [X] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [X] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        | 11.0
 SDWebImage Version      | 4.3.3
 Integration Method      | carthage
 Xcode Version           | Xcode 9.2
 Repro rate              | all the time (100%)
 Repro with our demo prj | n/a
 Demo project link       | https://github.com/ketzusaka/LinkIssues

### Issue Description and Steps

I'm attempting to integrate Braze (formally Appboy) into our an app using Carthage. The Braze SDK depends on FLAnimatedImage and SDWebImage. Since SDWebImage packages FLAnimatedImage into its source code I'm getting the following errors in my project (these are from sample project, but are identical other than the application name):

```
objc[92750]: Class FLAnimatedImage is implemented in both /Users/james/Library/Developer/CoreSimulator/Devices/F934324B-2FA4-499D-89AB-2B05FDB57AB2/data/Containers/Bundle/Application/166C0999-EF06-44AC-B9B7-7E690FE1E926/LinkIssues.app/Frameworks/FLAnimatedImage.framework/FLAnimatedImage (0x1062ec588) and /Users/james/Library/Developer/CoreSimulator/Devices/F934324B-2FA4-499D-89AB-2B05FDB57AB2/data/Containers/Bundle/Application/166C0999-EF06-44AC-B9B7-7E690FE1E926/LinkIssues.app/Frameworks/SDWebImage.framework/SDWebImage (0x1062715d0). One of the two will be used. Which one is undefined.
objc[92750]: Class FLWeakProxy is implemented in both /Users/james/Library/Developer/CoreSimulator/Devices/F934324B-2FA4-499D-89AB-2B05FDB57AB2/data/Containers/Bundle/Application/166C0999-EF06-44AC-B9B7-7E690FE1E926/LinkIssues.app/Frameworks/FLAnimatedImage.framework/FLAnimatedImage (0x1062ec5b0) and /Users/james/Library/Developer/CoreSimulator/Devices/F934324B-2FA4-499D-89AB-2B05FDB57AB2/data/Containers/Bundle/Application/166C0999-EF06-44AC-B9B7-7E690FE1E926/LinkIssues.app/Frameworks/SDWebImage.framework/SDWebImage (0x1062715f8). One of the two will be used. Which one is undefined.
objc[92750]: Class FLAnimatedImageView is implemented in both /Users/james/Library/Developer/CoreSimulator/Devices/F934324B-2FA4-499D-89AB-2B05FDB57AB2/data/Containers/Bundle/Application/166C0999-EF06-44AC-B9B7-7E690FE1E926/LinkIssues.app/Frameworks/FLAnimatedImage.framework/FLAnimatedImage (0x1062ec628) and /Users/james/Library/Developer/CoreSimulator/Devices/F934324B-2FA4-499D-89AB-2B05FDB57AB2/data/Containers/Bundle/Application/166C0999-EF06-44AC-B9B7-7E690FE1E926/LinkIssues.app/Frameworks/SDWebImage.framework/SDWebImage (0x106271a80). One of the two will be used. Which one is undefined.
```

I'd like to resolve this by removing the FLAnimatedImage library out of the SDWebImage project and configure the project to leverage FLAnimatedImage properly by setting it as a dependency in CocoaPods and Carthage. 

Since this is a pretty significant change I wanted to open an issue first and see if that'd be acceptable to the maintainers.

Thanks!

**Comment by dreampiggy** [comment]
FLAnimatedImage will totally removed in 5.x, with our native implementation solution for animated image, see #2140.

But this issue is a little confused. This issue seems only happend on Swift carthage package manager, Cocoapods can automatically handler this dependency issue since we add `FLAnimatedImage` as a dependency in Podspec.

I think we can check firstly and try to fix the carthage integration for 4.x Swift user.

**Comment by intoxicated** [comment]
It's because SDWebImage doesn't have Cartfile to handle dependency for carthage. So when someone installs SDWebImage with carthage, SDWebImage produces the framework with FLAnimatedImage embedded into it.

**Comment by dreampiggy** [comment]
@intoxicated Any suggestion to solve this ?
If we just simply add a `Cartfile` in the root path. Contains this:

```
github "Flipboard/FLAnimatedImage" ~> 1.0
```

However, after `carthage build`, this will also cause issue, because we create a git submodule in the `/Vender/FLAnimatedImage` folder. And the `SDWebImage.xcodeproj` also add these FLAnimatedImage files into the target source files...

**Comment by dreampiggy** [comment]
Or, could you please help us polish the [SDWebImageFLBridge](https://github.com/dreampiggy/SDWebImageFLPlugin) repo. This will be availble in 5.x because 5.x SD move all the FL-related files into another repo, not in the main repo. If people who need briding between these two framework, they can use that instead.

**Comment by Bucimis** [comment]
Hi @dreampiggy, are there any publicly available timelines for 5.x release?

**Comment by bpoplauschi** [comment]
We are closing in to releasing a 5.0.0-beta version. Stay tuned.
