### ISSUE TITLE
How to load images into webView async with the help of SDWebImage 

### ISSUE THREAD

**Issue by vinayakpal** [rs/SDWebImage#2284]
I'm using a web view in which text content loading with images in html file. but due to images loading web view not loading instantly. can you help how to use sdwebimage library to async load images into web view.

**Comment by dreampiggy** [comment]
For WebView resource load, you have only two ways.

The first one is `file://` schema. This means you can store the image into disk cache, and let `UIWebView`'s HTML use something like `<img src='file://local/file/url/path'>` This need you to write something called [JSBridge](https://github.com/marcuswestin/WebViewJavascriptBridge).

The second one, which is also the recommend way, it's using [NSURLProtocol](https://developer.apple.com/documentation/foundation/nsurlprotocol) to control all the resource loading process for `UIWebView`. Or using [WKURLSchemeHandler](https://developer.apple.com/documentation/webkit/wkurlschemehandler?language=objc) for `WKWebView. You just need to identify that the URLRequest is about image, and response the local file cached image as fast as possible.

You can also check some blogs about these, such as [this](https://medium.com/@kumarreddy_b/custom-scheme-handling-in-uiwebview-wkwebview-bbeb2f3f6cc1).

Since this topic is not related to SDWebImage framework usage, I just show the reference about it. Hope this can be helpful for you.
