### ISSUE TITLE
I do not understand the using of '__weak' in SDWebImageManager.m (Line: 153)

### ISSUE THREAD

**Issue by cocoongg** [rs/SDWebImage#2321]
SDWebImage Version      4.3.3

### Issue Description and Steps

In the SDWebImageManager.m(Line:153), the code is:
` __weak SDWebImageCombinedOperation *weakOperation = operation;`

And, using `strongOperation` in the `done` block, does the operation retain the `done` block?
Why should we use the `__weak SDWebImageCombinedOperation *weakOperation = operation`?

**Comment by dreampiggy** [comment]
Well...From current design, that `SDWebImageCombinedOperation` will not be retained by `SDImageCache`, because the `queryCacheOperationForKey:options:done:`'s  `done` block is a non-escape closure (callback in the stack but not pass to some other variable).

But however, in 5.x we support custom cache #2278. So at that time user-provided cache may retain this block if they like. Using `weak` can avoid some issue.

And, if the closure is non-escape, does that using `weak-strong` really cause some issues ?
