### ISSUE TITLE
Image Resizing issue after image loading

### ISSUE THREAD

**Issue by vinayakpal** [rs/SDWebImage#2345]
Hi,
I'm using SD web image pod to display async photo in the table view cell. but for every dirfferent cell in need to resizing my image after loading using image.sd_setImage(URL:) but when i tried to get the image frame's height and width it shown me 0.0 . please helpmeet to resolve this issue.

**Comment by dreampiggy** [comment]
View is view, image is image. `UIImageView` have its own bounds to identify the actual rendering image's size. Where the `UIImage`'s size property represent the image resolution ( pixel width / scale ).

I think your problem is that you didn't specify your cell's imageView's frame before loading the image. If you want your imageView's frame to be exact what image resolution, call `imageView.size = image.size` in the completion block of `sd_setImageWithURL:completion:`...

**Comment by vinayakpal** [comment]
yes, I call for UIImage size in completion block and it starts giving height and width but still it some times returns 0.0 and but again returns original value when cell refreshed
