### ISSUE TITLE
UIScreen.scale and output images

### ISSUE THREAD

**Issue by larsacus** [rs/SDWebImage#2358]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | iOS
 Platform Version        | 11.x/10.x
 SDWebImage Version      | 4.1.2
 Integration Method      | cocoapods
 Xcode Version           | Xcode 9.3
 Repro rate              | 100%
 Repro with our demo prj | Probably
 Demo project link       | n/a

### Issue Description and Steps

Good day! This may or may not be an issue depending on the design intent around images for this library. I've recently come across what _appears_ to be an issue in SDWebImage where downloaded remote images have an incorrect `UIImage.scale` for their device scale if the URL doesn't contain any scale information (`@3x`, `@2x`, etc). This results in images with implicit sizes that are _waay_ bigger than they should be, which confuses the implicit sizing of UIImageView, which ultimately affects auto-layout and layout in general.

#### Example

Given a `UIImageView` inside of an arbitrary layout with a given fixed width (`375`) and dynamic height, I would like to fetch a remote image and have the resulting image auto-sized with auto layout. I know the aspect ratio I would like for this image to have, let's say `3:2` for this example.

Given my URL parameters (`https://placekitten.com/{x}/{y}`), a width, aspect ratio, and screen scale (let's say iPhone Plus — 3x scale), I have enough information to construct a URL to fetch a remote image:

``` swift
let aspect: CGFloat  = 3.0/2.0
let scale = UIScreen.main.scale
let kittenURL = URL(string: "https://placekitten.com/\(Int(imageView.bounds.width*scale))/\(Int(imageView.bounds.width/aspect * scale))")! // https://placekitten.com/1125/750
```

The resulting image that is returned using SDWebImage for this URL has an `image.scale == 1.0` and `image.size = {1125.0, 750.0}`. This makes the resulting implicit content size of `UIImageView` to be `{1125.0, 750.0}` instead of the correct parameters of `{375.0, 250.0}` @ 3x scale. This affects not only the implicit content size, but the image content mode resizing parameters of `UIImageView` with an image it thinks is much larger than it actually is.

The only mentions of the scale API on `UIScreen.mainScreen` are located in the GIF construction in `UIImage+GIF.m:42` and in `SDWebImageCompat.m:48`, which appears to use it exclusively to know if it needs to even search for the `@`-scale modifiers in the original URL. I can hack usage of the `screenScale` API into `SDWebImageCompat.m:50` as the default scale and this works marvelously (for my specific application), but I doubt that is the correct solve for this issue.

Do you have any guidance on how to achieve the correct output that I am looking for? I searched for relevant issues and didn't find anything that sounded similar to this. If this does in fact sound like a bug internally, what can I do to help this get resolved?

Thank you in advance! 🍻

**Comment by dreampiggy** [comment]
This feature is already added in #2266. Which allow you to provide a extra scale factor arg to specify the target image scale. This will effect all the coders to use that information as scale factor and we will not call create a extra `UIImage` instance by grabing the previous CGImage and the new scale factor. See more in that PR.

```swift
imageView.sd_setImage(with: url, placeholderImage: nil, options:[], context: [.imageScaleFactor: 3], progress: nil, completed: nil)
```

In 4.x, seems we do not have a plan to add this feature. However, current you have one solution:
You can try to use [cache key filter](https://github.com/rs/SDWebImage/blob/master/Docs/HowToUse.md#using-cache-key-filter), to remap your remote URL format (like you say `https://placekitten.com/{x}/{y}`), to a string key that contains the scale factor(like `https://placekitten.com/{x}/{y}@3x.jpg`). Then the build-in process in 4.x will treat this url as a scaled url and will use 3x for scale factor.

This sounds a little trick, but since current we do not have plan to add a entire `context` arg in 4.x version, there are no something other good way to solve this.

**Comment by larsacus** [comment]
I implemented the above workaround and it does in fact work for the images in question. Since this method affects all image requests in my application, it will require a regression on images. I'm confident this is the better method for image fetching for my application, though.

Any timeline on 5.0 release date?

**Comment by dreampiggy** [comment]
@larsacus 5.x seems take so long time. We have to wait for #2285 to finish.

About current workaround - a more tricky way in 4.x. Since the `cacheKeyFilter` accept a `NSURL` instance, which original from the View Category method, you can try to pass extra information on that `NSURL` instance, for example, using [setResourceValue:forKey:error:](https://developer.apple.com/documentation/foundation/nsurl/1413819-setresourcevalue) or Objective-C associate object way...Then in your `cacheKeyFilter` block, check the asscoiate value about scale factor, and return a modified cache key with `@2x.` or `@3x.`
