### ISSUE TITLE
How does SDWebImage handle cookie?

### ISSUE THREAD

**Issue by qinqi777** [rs/SDWebImage#2365]
I use AFNetworking to get the URL of an image, and then call [UIButton sd_setImageWithURL:], but the image was wrong. But it's right when using AFN.
So I guess maybe SD removed cookie when it request.
What the image shown depended on the cookie in response of request: "get the URL of image".

我用AFN请求到一个图片的地址，其实是图形验证码，想要显示正确的图片，依赖于cookie，但是我用SD去加载的话，图片始终都是错误的。
所以我想问，是不是SD会在请求的时候移除cookie？

**Comment by dreampiggy** [comment]
SDWebImage use the standalone `NSURLSession` instance, which create from `NSURLSessionConfiguration.defaultSessionConfiguration`. So if you set the Cookie using `NSHTTPCookieStorage. sharedHTTPCookieStorage`, then these cookie information will be grab during NSURLSession network download.

I guess your problem is that you does not store the Cookie information to the shared cookie storage, or using another session configuration for download. So you can set a breakpoint, or using Charles network debugger, to check why these cookie was lost
