### ISSUE TITLE
Error Domain=NSPOSIXErrorDomain Code=28 "No space left on device"

### ISSUE THREAD

**Issue by codefei** [rs/SDWebImage#2366]
We use SDWebImage download remote image from network. The SDWebImage use NSURLSession download image.

But we got strange error log that somebody cannot show image because got error `Error Domain=NSPOSIXErrorDomain Code=28 "No space left on device"` 
This error happens rarely and cannot reproduce.

And we collect disk usage info and make create file test. We cannot find abnormal phenomena.

When the user met the problem reopen our app again and image can show again.

This is very strange, anyone met the same problem? I can sure this is not SDWebImage issue, seems like system issue.

**Comment by dreampiggy** [comment]
This will happen when the system's left space is really low. However, after trigger this error, iOS system will try to collection the all App's cache, System cache and remove them in the order (Like a Jetsam for disk). So next time you call store disk, there may be more space and no error occur.

This can not be easilly solve, because it's actually disk space issue. We can just passthrough the error to our developer to let it do something to show this to the end-user

**Comment by bpoplauschi** [comment]
```obj-c
kPOSIXErrorENOSPC             = 100028, /* No space left on device */
```
This is a standard system error. As @dreampiggy said, we can just surface this error, we can't control the conditions under which this error occurs.

**Comment by doraeqing** [comment]
Hello, have you solved this problem?

**Comment by pradeep-ios-ucodesoft** [comment]
Device has enough space, but still occur this issue on serial API calls ( Approx. 650+). Anyone have solution for this.

**Comment by gl-lei** [comment]
https://stackoverflow.com/questions/67318867/error-domain-nsposixerrordomain-code-28-no-space-left-on-device-userinfo-kcf
