### ISSUE TITLE
iOS 11 FLAnimatedImage object leak. Bug

### ISSUE THREAD

**Issue by papanton** [rs/SDWebImage#2377]
- [x] ###

 New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name              | iOS
 Platform Version           | 11.0
 SDWebImage Version   | 4.4.1
 Integration Method       | cocoapods
 Xcode Version               | Xcode 9
 Repro rate                      | 100%
 Demo project link          | https://github.com/papanton/SD_CrashProject

Memory grows uncontrollably during gif loading. Eventually, the app crashes due to memory issues. Memory warning never triggered. Demo project provided, hooked up to a source of gifs. Scroll on iOS 11 Device real device and it should crash. This issue occurs on iOS 11 Devices but not on iOS 10. On an old iPhone 5 running iOS 10 that I have, there are no issues.

After a bit of poking around with instruments, I realized there is a FLAnimatedImage leak. FLAnimatedImages are initialized but not deallocated.

Please advice, or let me know if you have any further questions.

This is instruments for iOS 10. See how the memory is getting deallocated:

<img width="1286" alt="screen shot 2018-07-05 at 1 07 06 pm" src="https://user-images.githubusercontent.com/3289183/42345895-aeed5b0c-8055-11e8-9991-6892e17e3cda.png">

This is ios 11 iPhone X. See how FLAnimatedImage has not been deallocating. App Crashed. 

<img width="1286" alt="screen shot 2018-07-05 at 1 16 22 pm" src="https://user-images.githubusercontent.com/3289183/42345926-c640dbb2-8055-11e8-8221-005fcd70be82.png">

**Comment by QEllis** [comment]
Me too

**Comment by dreampiggy** [comment]
@papanton Hi. Have you tried to disable that weak memory cache introduced in #2379 ? You can test your demo with that commit using Cocoapods.

**Comment by papanton** [comment]
sounds good ill give it a shot thanks @dreampiggy

**Comment by papanton** [comment]
@dreampiggy I disabled the weak memory cache on the didFinish call in Appdelegate but this did not seem to fix the crash. One thing that might be creating problems is that the system memory warning never actually gets triggered. I updated my test project if you want to take a look.

**Comment by dreampiggy** [comment]
@zhongwuzw I guess that `setImageBlock` in the previous version may retain the imageView as well. However, this `setImageBlock` will finally get released because this is not actually a retain cycle. When image load finished, the `sd_setImageLoadOperation:` associated operation will be removed. So that the imageView should be dealloc.

And also, if you don't disable `FLAnimatedImageView.sd_cacheFLAnimatedImage` option, this `FLAnimatedImage` instance will be stored to memory cache. Which is kept alive until you remove it or memory warning cause it been purged.

The insteresting behavior is that `One thing that might be creating problems is that the system memory warning never actually gets triggered`. Which may be the root case.

**Comment by papanton** [comment]
@zhongwuzw Setting the maxMemoryCountLimit actually works, but also limits the cache for regular images. I would prefer if I relied on the actual memory warnings for purge caching instead. If we find no solution I will probably go with your suggestion, too many crashes in production from this.

**Comment by zhongwuzw** [comment]
@dreampiggy Yeah, it's not retain cycle. Just would leads some extra objects alive and increase the memory.
TBO, I don't reproduce the crash, I use iPhone6+ and `iOS11.3.1` and `master` branch. I  `Instruments` it, and the `VM allocation` increase to `1.x G`  and then memory would down back to reasonable footprint. And also I received the memory warning.

**Comment by papanton** [comment]
@zhongwuzw are you using my test project? @dreampiggy have you been able to replicate from the issue? My memory increases to about 550mb before the crash with an iPhone X

**Comment by bpoplauschi** [comment]
@zhongwuzw I would not rely on `NSString` to always allocate memory, as the way strings are used, reused and allocated into global access memory is not totally known. I would feel better using another class, like `NSNumber` or `NSData`

**Comment by dreampiggy** [comment]
@papanton Sorry maybe I miss this issue. The demo you provide seems not works because of that API failed in this url : `https://dashboard.stickerpop.co/api/animated`. Could you provide a update and I'll check soon ?

```json
{"message":"Unauthenticated."}
```

**Comment by papanton** [comment]
@dreampiggy opened up that endpoint, the project should work now. I apologize for that.

**Comment by dreampiggy** [comment]
@papanton It seems that `UIApplicationDidReceiveMemoryWarningNotification` not been called when the OOM occured. This may because of that this notification is always be sent on the main queue by UIKit. Sometimes the OOM cause by `Image/IO` decoding process. So that if the current runloop is full of Core Animation task (GIF image need CALayer to show frames, which may consume and cause allocation of memory) , the system will already kill your application because memory warning notification is delayed...

The better solution, maybe it's to limit the memory cache's size. You can try set `SDImgeCache.maxMemoryCost` or `SDImageCache.maxMemoryCountLimit` to a smaller size which is suitable for the device. (Calculate the number based on device total memory or dynamic change this propery)

In #2374, I'll try to provide more detail control about limit the memory usage. For example, you can disable store the `FLAnimatedImage` to memory cache (Using `sd_cacheFLAnimatedImage` property), cause it dealloc as soon as imageView dealloc.

**Comment by dreampiggy** [comment]
@papanton 4.4.2 is out. Could you please read me reply above (I analysis the reason and provide some help), and try the new version ?

You can disable the `FLAnimatedImage` memory cache by using `FLAnimatedImageView.sd_cacheFLAnimatedImage = false`, so that the image instance will dealloc immediatelly (But which will cause frame drop because of disk cache query)

**Comment by papanton** [comment]
Hey @dreampiggy thanks for all the help, I ended up setting the maxmemory cost and it seems to be performing well. You can close this issue.

**Comment by dreampiggy** [comment]
@papanton The animated image is a big task to talk about. If you're still care about the animated image solution , you can consider to try [Animated Image](https://github.com/rs/SDWebImage/wiki/Advanced-Usage#animated-image-50) in 5.0.0-beta
