### ISSUE TITLE
Let operationClass of SDWebImageDownload subclass SDWebImageDownloaderOperation or conform SDWebImageDownloaderOperationInterface

### ISSUE THREAD

**Issue by zhongwuzw** [rs/SDWebImage#2396]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Description and Steps

From the comments of `operationClass`, we can see `operationClass` needs subclass `SDWebImageDownloaderOperation`. But actually we allow users to set `operationClass` which subclass `NSOperation` and conforms to `SDWebImageDownloaderOperationInterface`(Refer to the implementation of `- (void)setOperationClass:(nullable Class)operationClass`). 

So, if we allow this behavior, we should change all method signature with `SDWebImageDownloaderOperation` to `NSOperation< SDWebImageDownloaderOperationInterface>`.

**Comment by zhongwuzw** [comment]
@dreampiggy @bpoplauschi @skyline75489 What's your opinion? 🤔

**Comment by dreampiggy** [comment]
@zhongwuzw No. You don't need to subclass `SDWebImageDownloaderOperation`.

The comment here is show `The best practice is to subclass `SDWebImageDownloaderOperation` because some of methods like `addHandlersForProgress:completed:` is hard to implement your own.

The only limit for custom class, is that your class's object should be `NSOperation<SDWebImageDownloadOperation>`, that's it.

**Comment by dreampiggy** [comment]
@zhongwuzw You're using `master` branch :)
I remember in 5.x I've changed all of this `SDWebImageDownloadOperation *` to `NSOperation< SDWebImageDownloadOperation>`, you can check that...

In `master` branch, yes we write something like `SDWebImageDownloadOperation` in the code, however, we also update the `SDWebImageDownloaderInterface` method when we use and add `@required` annotation. So runtime crash will not happend. But anyway, seems a ugly code style because of historical reason.

If you want to change it, it's good. But actually, that seems does not cause issue...The 5.x branch is now far away from master branch, and it's hard to merge (Because of many renaming issue, cause git diff show strange).

**Comment by zhongwuzw** [comment]
>when we want to call something method on SDWebImageDownloadOperation *, we also update the SDWebImageDownloaderInterface method in @required annotation

@dreampiggy Emm,maybe not, e.x. You can see this [line](https://github.com/rs/SDWebImage/blob/master/SDWebImage/SDWebImageDownloader.m#L321).

So should we need to handle these issues? or just let it be. 😂

**Comment by dreampiggy** [comment]
@zhongwuzw Seems you're correct. In 5.x I add it as `optional` and check it before use. See [here](https://github.com/rs/SDWebImage/blob/5.x/SDWebImage/SDWebImageDownloader.m#L335).

Though since it's a protocol, you can use any network stack does not use NSURLSession at all (Like my company's app build from Cronet from the scratch). But nearlly 99% Apps use NSURLSession 😅 

If you're desired, you can change master branch with that `NSOperation< SDWebImageDownloadOperation>`, and add that optional `dataTask` method in `SDWebImageDownlaodInterface`.

**Comment by zhongwuzw** [comment]
@dreampiggy 👍 ， `Cronet`'s performance is big win against `NSURLSession` in your product environment? 🤔

**Comment by dreampiggy** [comment]
@zhongwuzw Actually, the network tranfer performance seems no big benefit. However, we have many business reason to build from Cronet. The most reason is that Cronet is a C++ implementation, which can build a cross-platform sulotion for network, instead of using NSURLSessiom on iOS && HttpUrlConnection on Android, to write the same logic twice. We have some custom feature For example, sometime we need support HTTPS-2 for lower fireware like iOS 8 && Android 4.4. And we need some network stack feature like HTTP-DNS, custom encrpt-decrypt, detailed cache control, etc...So maybe this is why some user choose this.

But, from my personal mind, I don't think it's a good solution for normal apps because it may not have many limitation faced by us :(

**Comment by zhongwuzw** [comment]
@dreampiggy Thanks for your detailed description 💯 . Yeah, discard build-in network framework has many pros, like can totally control network behavior, cache, proxy, new protocol support ...., but also has some cons, like increased app size, maybe more energy penalty(It's just my guess, I think `Apple` should always know utilize their own system than `Google` 😢 ).
