### ISSUE TITLE
GIF loads rotated if imageview was previously used to load JPG

### ISSUE THREAD

**Issue by ericeddy** [rs/SDWebImage#2402]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios 
 Platform Version        | 10+
 SDWebImage Version      | 4.4.2
 Integration Method      |  cocoapods 
 Xcode Version           | Xcode 9.4
 Repro rate              | 100% given the steps
 Repro with our demo prj | - -
 Demo project link       | - -
  

### Issue Description and Steps
When I load a Gif into the same FLAnimatedImageView that was previously used to load a JPG(which was taken with the camera), the gif appears to be rotated. But if I load that same cached Gif without it previously loading the JPG, the Gif isn't rotated. 

This is happening in a tableview which has tableviewcells that have FLAnimatedImageView's on them. 
- Have a table view with cells that are half the screen tall ( makes the cell reloading happen quicker )
- Have a data source provide 5 gif urls and then 5 Jpg urls
- Open the VC, see the Gifs load and play properly
- Scroll to the Jpgs, see them load and display properly
- Scroll back to the Gifs, any cell that was previously displaying a Jpg will now be displaying their Gif rotated

Similar Issue: https://github.com/rs/SDWebImage/issues/1317  

From what I've found in my searches this has something to with the JPG having EXIF metadata and the Gif not, but I'm unsure what I can do to fix the issue.

One of the JPG's causing the issue: https://skrumble-dev-assets.s3.amazonaws.com/chats/5b4cadeaf1ad970f5063416b/4744214435480065278.jpg

**Comment by ericeddy** [comment]
Even easier way to reproduce it is, 
I select a JPG from my Photo library & load it into an image view, then I select a gif from my photo library and load it into the same image view, the displayed Gif is rotated.

**Comment by dreampiggy** [comment]
It seems a FLAnimatedImageView bug. UIImageView and our decoder always process the EXIF to image orientation correctly.

Could you please help to provide a demo that can trigger this issue ? Maybe we can figure it out quickly.

**Comment by ericeddy** [comment]
Here's a test repo link:
https://github.com/ericeddy/FLAnimatedImage-RotationIssue

I've noticed that using just any jpg doesn't cause it, like random jpgs from the internet cause it to occur sporadically,
But using images taken with the phone's camera will cause it 100% of the time, and using a landscape photo vs using a portrait photo will add an extra 90 degrees to the rotation

**Comment by dreampiggy** [comment]
@ericeddy After some test and my experiment, I can confirm it's a **BUG** in `FLAnimatedImage` third party library itself. I've create a MR to the [FLAnimatedImage](https://github.com/Flipboard/FLAnimatedImage/pull/214) repo. You can push them to merge it and solve this problem.

Now I can talk about the reason that cause this problem. At first, you should have basic knowledge of UIView-CALayer, if you don't know them, you should watch [Understanding UIKit Rendering](https://developer.apple.com/videos/play/wwdc2011/121/) before reading the below.

### What cause this problem 

`FLAnimatedImageView`, it's a UIImageView subclass, which manually specify [CALayer.contents](https://developer.apple.com/documentation/quartzcore/calayer/1410773-contents) with the current rendering frame's `CGImage`. And they use a CADisplayLink as a timer, to refresh current frame, finally produce the visual animation.

However, `CALayer` itself, contains a private property, called `contentsTransform`. You can check the private header [here](http://developer.limneos.net/index.php?ios=11.1.2&framework=QuartzCore.framework&header=CALayer.h). `CALayer` will calculate current `UIImage.imageOrientation` and translate to `CGAffineTransform` to render the bitmap. Why they to do this it's because `CGImage` does not actually take rotation when you create UIImage with [-[UIImage imageWithCGImage:scale:orientation:]](https://www.google.com/search?q=UIImage+imageWithCGImage&oq=UIImage+imageWithCGImage&aqs=chrome..69i57.2422j0j7&sourceid=chrome&ie=UTF-8), The both `scale` and `imageOrientation` are just hint to the CALayer's property `contentsScale` and `contentsTransform`. So that `CALayer` use the `contentsTransform` to actually do rotation about the bitmap. What to say, actually, `CALayer` draw its contents, based on the both publich `CALayer.transform` and private `CALayer.contentsTransform`.

See the screenshot during View Debug and print out the CALayer information. The actually `CALayer.contents` bitmap show the correct orientation, but the rendering result cause a rotation.


<img width="1440" alt="2018-07-27 9 31 10" src="https://user-images.githubusercontent.com/6919743/43323532-8096eff2-91e4-11e8-85be-55ced6521031.png">


After I use KVO to observe this `contentsTransform` changes, I found that the only write on this property was happend on `-[UIImage setImage:]` function call with a **non-nil** `UIImage`. The **non-nil** is really important. Because FLAnimatedImage original code only trigger it with a nil object when `-[FLAnimatedImageView setAnimatedImage:]` was triggered.

<img width="1552" alt="2018-07-27 8 09 26" src="https://user-images.githubusercontent.com/6919743/43323566-986e304a-91e4-11e8-93da-42ab7bd147ad.png">


So now, you may know the reason. Right, the previous JPEG image which contains non-Up image orienation change the `conrtentsTransform`, but the new `FLAnimatedImage` does not clear that. I check the current FLAnimatedImage code and finally find the bug. The root case is that `-[FLAnimatedImage setAnimatedImage:]` does not do the correct thing, to reset the super `UIImageView` state about image.

```objective-c
- (void)setAnimatedImage:(FLAnimatedImage *)animatedImage
{
    if (![_animatedImage isEqual:animatedImage]) {
        if (animatedImage) {
            // Clear out the image.
            super.image = nil;   // -> This will not reset `contentsTransform`, not actually "Clear out the image."
            // Ensure disabled highlighting; it's not supported (see `-setHighlighted:`).
            super.highlighted = NO;
           //...
    }
}
```

### Solution

The naive solution, it's quite simple, firstlly call `super.image = non-nil image` and then call `super.image = nil`. Only one line code and the issue disappear.


```diff
 {
     if (![_animatedImage isEqual:animatedImage]) {
         if (animatedImage) {
             // Reset `contentsTransform` state
+            super.image = animatedImage.posterImage;
             // Clear out the image.
             super.image = nil;
             // Ensure disabled highlighting; it's not supported (see `-setHighlighted:`).

``` 

From my personal opinion, I think they should always call `[super setImage:]` during `[FLAnimatedImageView setAnimatedImage:]`. If you don't call super, you may loss internal consistent behavior during subclass. But anyway, this fix is much simpler.

### Current workaround ?
Yes. FLAnimatedImage seems no longer maintained, though I fire the PR, it may take long time to merge in (or may be forever :) ). For our `FLAnimatedImage+WebCache`, the simple way to fix this, it's just use the code above, call `super.image = animatedImage.posterImage;` before `super.animatedImage = animatedImage`. I will create another PR fix for SDWebImage/GIF subspec.

**Comment by ericeddy** [comment]
Thank you for such a thought out and fast response!
I think for the meantime I'm going to go ahead with your suggestion and use 5.0.0-beta, I tried out how it works in the demo and it seems to be working well, 

Again, Thank you for all this work, I really appreciate it!
