### ISSUE TITLE
App crashes when load many images from firestore - swift

### ISSUE THREAD

**Issue by SamboVisal** [rs/SDWebImage#2418]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [ ] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

 Info                    | Value                               | 
-------------------------|-------------------------------------|
 Platform Name           |  ios 
 Platform Version        |  10.13.0 / 11.0 
 SDWebImage Version      | 4.2.0
 Integration Method      | cocoapods
 Xcode Version           | Xcode 9
 Repro rate              |all the time (100%)
 Repro with our demo prj | It happens with my demo project
 

### Issue

I was trying to load imageUrl from firestore and load it to my application. Initially i tried to load around 4 or 10 images and it works fine. But when i want to load around 20 images and my app crashes and it also shows error in my console states that `Message from debugger: Terminated due to memory issue
`.

**Comment by bpoplauschi** [comment]
@SamboVisal thanks for taking the time do describe the issue. We had similar issues in the past, usually because the iOS system cannot handle decompressing of many images at once, due to the memory spike that causes an out-of-memory crash. You can look at similar issues here: https://github.com/rs/SDWebImage/search?q=Terminated+due+to+memory+issue&type=Issues

One thing you can try is:
```objective-c
[[SDImageCache sharedImageCache] setShouldDecompressImages:NO];
[[SDWebImageDownloader sharedDownloader] setShouldDecompressImages:NO];
```

Also check out these points about reducing the memory footprint: https://github.com/rs/SDWebImage/issues/2252#issuecomment-375891085

One thing I recommend is just running the app through instruments and inspecting the memory.

**Comment by SamboVisal** [comment]
Now i am having another question. For example, images are downloading and suddenly internet has been disconnected and image will not loaded anymore. But when internet is back i want it to continue to download from it stopped. How to solve this? Thank you

**Comment by fschaus** [comment]
Hi guys,

I am having a very similar issue (using GIFs with v5.0) but can't get hold of the of the shouldDecompress method/ variable in Swift (went through the doc but couldn't find it)... 

Do you mind letting me know how to set off the decompression in Swift? I'll try to see if this works before opening a new issues (if necessary).

Thanks!
Francois

**Comment by dreampiggy** [comment]
@fschaus Hi. The SDWebImage 5.x, change that global control level `shouldDecompress`, to the `SDWebImageOptions` level, which allow you to control each image request instead of a global one (Because some small images, it's no need to trun off that force decode feature).

See the migration guide here : [5.0-Migration-guide](https://github.com/rs/SDWebImage/wiki/5.0-Migration-guide)

You should now use like this to disable the force decode feature:

```swift
imageView.sd_setImage(with: url, placeholderImage: nil, options: [.avoidDecodeImage])
```

**Comment by fschaus** [comment]
Thanks for the input, I should have looked in the migration guide. 

So I profiled a bunch of tests on my app to get to the bottom of this and see really weird behavior. See the link below for the details:
• My debug version runs as expected - once loaded my app allocates ~70Mb in memory (which is in line with what I saw previously when I was using KF). After a bit of usage (message loading + images) it goes up to 120-13Mb, rarely above (maxCache works) and flushes itself once the app enters background.
• My release/ prod scheme however shots straight to 160Mb at load, quickly goes to 300Mb (or more if I keep loading but then more often than not crashes) which doesn't respect my cache limit. If I don't turn off decoding the memory doesn't get flushed once the app enters the background (it decoding is off but still retains more than expected at 120-140Mb vs. 20-30Mb w/ my debug scheme).
• I use 5.0 beta 2, with a mix of fixed images and gifs (the initial loading screens only have fixed images). I also tested with UIImageView and AnimatedImgView but that makes no difference
• I also used Kingfisher to compare and its behavior with my prod release was similar to SDWI with my debug scheme. In all cases I use the "default" manager settings (except decode that I toggle on/ off for one of my use case).

My detailed tests are here: [https://drive.google.com/open?id=1HIRHttQYn1NIJr0Omb9BG2FLOeWa8E_9](url)

I am not deep enough in this library nor in iOS image frameworks to understand how they differ between the debug and the release scheme but I feel like the culprit is likely there (given the vastly different behavior observed).

I really like SDWebImg as it is the only library with a strong gif manager which allows me to have a single cache/ image processor for PGN & Gifs (I had a weird convoluted kingfisher + FLAnimatedImg setup before) and like how more flexbile SDWebImg is (e.g., add fade, progress bar, etc.) so really hope we can get to the bottom of this together J 

Thanks!
Francois

**Comment by bpoplauschi** [comment]
@fschaus thanks for the detailed write-up, we will look into this issue in detail.
For now, I think it's a good idea to move your scenario to a separate issue, to keep the conversation clean. I don't think it's the exact same issue as the one in the description.

**Comment by bpoplauschi** [comment]
Moved @fschaus conversation to #2448

**Comment by bpoplauschi** [comment]
@SamboVisal can we close this issue now? Did you get what you needed?
