### ISSUE TITLE
- (void)storeImage:(UIImage *)image ...  toDisk:(BOOL)toDisk  Ignores scale on reload

### ISSUE THREAD

**Issue by chresko** [rs/SDWebImage#576]
the method:

```
- (void)storeImage:(UIImage *)image imageData:(NSData *)imageData forKey:(NSString *)key toDisk:(BOOL)toDisk
```
when writing to disk as PNG (no name extension, hashed), ignores scale. so if you downloaded an image, processed it (scale, crop, etc) for a retina display, and then close your app and reload the image from disk, it will be 2x the size of what it should be (since you're not also writing the scaling factor to disk with the data) and you're implicitly setting the scale factor to 1.0 on decode.

**Comment by ebfg** [comment]
@chresko any update on this? We just ran into the same problem

**Comment by ikesyo** [comment]
This should be reopened since this is now re-broken by the change in #1540.

**Comment by tirrorex** [comment]
Hum, so this is where my bug is coming from, any idea on how to prevent this?
The only workaround i have right now is to set my contentMode to aspectFit but unfortunatly since the image is now bigger i have to implement custom code in order to resize the imageView after each load, very annoying imo.
