### ISSUE TITLE
Give a look at FLAnimatedImage for animated GIF 

### ISSUE THREAD

**Issue by akhenakh** [rs/SDWebImage#733]
https://github.com/Flipboard/FLAnimatedImage

**Comment by maha-ghonam** [comment]
@Bluezen i have the same problem , did you find a solution to it?

**Comment by Bluezen** [comment]
@maha-ghonam  [This fork](https://github.com/liyong03/SDWebImage) of SDWebImage has a very nice solution yes. It prevents an UIImage to be created uselessly if you plan to handle GIFs with another library (You should have a look at [these particular lines](https://github.com/rs/SDWebImage/blob/d3567259f2d1c8a1b191563aef1357eed081b600/SDWebImage/UIImage%2BMultiFormat.m#L25-28)) and it correctly handles NSData caching. 
You can use [YLGIFImage](https://github.com/liyong03/YLGIFImage) to handle the GIFs and continue to use SDWebImage thanks [SDWebImage-YLGIFImage](https://github.com/liyong03/SDWebImage-YLGIFImage) and the specified fork of SDWebImage.
Or you could use [DFImageManager](https://github.com/kean/DFImageManager) instead of SDWebImage if you really want to use FLAnimatedImage.

**Comment by maha-ghonam** [comment]
@Bluezen thanks for your reply.
i have tried the SDWebImage-YLGIFImage to handle GIFs but the memory increased incredibly while loading the GIFs and blocks the UI too until finishing.

about DFImageManager it seems to work great but it didn't handle disk cache and the images are downloaded every time the app is launched.
 
is there any way to handle downloading and displaying GIFs with little memory usage and high performance?

**Comment by Bluezen** [comment]
@maha-ghonam YLGIFImage works perfectly well for me, even with heavy GIFs it uses very low memory. Have you made your tests on real devices? About the UI blocked you should check your code, it shouldn't be SDWebImage-YLGIFImage's fault. Good luck!

**Comment by kean** [comment]
I know it's really old, but just for the reference

> about DFImageManager it seems to work great but it didn't handle disk caching and the images are downloaded every time the app is launched

It does not reinvent caching and relies on NSURLCache which supports standard [HTTP caching](https://tools.ietf.org/html/rfc7234). Here's a [guide](https://github.com/kean/DFImageManager/wiki/Image-Caching-Guide) on this topic. If your images are not cached then you have a server with misconfigured HTTP caching. If you don't have control over the sever there are [ways](https://github.com/kean/DFImageManager/wiki/FAQ#cache_q01) to bypass HTTP cache-control headers.

**Comment by hilen** [comment]
Take a look at this : https://gist.github.com/hilen/8ef4a810406051e8f0c1

**Comment by bpoplauschi** [comment]
By merging #1575 into the 4.x branch, I think we can close this thicket. Feel free to test it and let us know if it works.
