### ISSUE TITLE
sd_setImageWithPreviousCachedImageWithURL method polls disk cache synchronously

### ISSUE THREAD

**Issue by DimaVartanian** [rs/SDWebImage#793]
Stumbled onto this while working on my pull request and it seems like an error.

`- (void)sd_setImageWithPreviousCachedImageWithURL:(NSURL *)url andPlaceholderImage:(UIImage *)`, which is assumed to be called on the main thread, calls `[[SDImageCache sharedImageCache] imageFromDiskCacheForKey:key];
` synchronously.

Shouldn't it be using something like `- (NSOperation *)queryDiskCacheForKey:(NSString *)key done:(void (^)(UIImage *image, SDImageCacheType cacheType))doneBlock`?

As a side note, this method is also missing from `UIButton`. Was that intentional?

Thanks!

**Comment by mitchellporter** [comment]
Has any progress been made on this?

**Comment by bpoplauschi** [comment]
Looks like it didn't.

**Comment by zyi1992** [comment]
Any progress?

**Comment by DimaVartanian** [comment]
I'll take a look about adding this today.

**Comment by dreampiggy** [comment]
You should considerate the RunLoop as well. UIKit(Core Animation) will do layer composition during the same runloop, so if you call these:

```objective-c
imageView.image = image1;
sleep(1);
imageView.image = image2;
```

is different from

```objective-c
imageView.image = image1;
dispatch_async(queue, ^{
    sleep(1);
    dispatch_async(dispatch_get_main_queue(), ^{
        imageView.image = image2;
    });
});
```

The second one will trigger a flashing because image1 will be rendered, the first one will just show image2 but with a lag because of blocking the main queue.

So, next, what cases do you need ? If you want to keep the current image for non-reused imageView, use `SDWebImageDelayPlaceholder` instead.

If you want to use it for reused imageView (tableViewCell/collectionViewCell), current implementation will force to query the memory-disk cache. So this is adoptable for normal use case.(You'll never disable memory cache when you decide to use this method, right ?). For advanced control on reused-imageView caching, you need to implement it yourself.

**Comment by dreampiggy** [comment]
If you think that disk cache is really really important(if the disk cache contains the image, load it, don't care about blocking main queue!), use `SDWebImageQueryDiskSync` options with the normal public API(`sd_setImageWithURL:) can solve this issue.

If you think that you need keep a high frame rate, you just need to query memory cache, so use `SDWebImageCacheMemoryOnly` is OK.

**Comment by dreampiggy** [comment]
#2175 Merged. Consider using `SDWebImageQueryDiskSync` instead.
