### ISSUE TITLE
[SDWebImageCombinedOperation setCancelBlock:]: message sent to deallocated instance

### ISSUE THREAD

**Issue by kirualex** [rs/SDWebImage#798]
I get this crash in my app. I'm doing a lot of prefetching, don't know if it's relevant to this issue.

**Comment by Air-Craft** [comment]
Just been looking into this as it's causing a significant number of crashes amongst users in the app I'm working on. Might it be a BAD_ACCESS in disguise (memory gets freed and repurposed into another class type resulting in the "cancel" or "setCancelBlock" to crash)?  

A bit of guesswork here but might this be a result of a stack overflow due to a circular loop here:

~L244 
            operation.cancelBlock = ^{
                [subOperation cancel];
                
                @synchronized (self.runningOperations) {
                    [self.runningOperations removeObject:weakOperation];
                }
            };

and ~L318

    - (void)cancel {
        self.cancelled = YES;
        if (self.cacheOperation) {
            [self.cacheOperation cancel];
            self.cacheOperation = nil;
        }
        if (self.cancelBlock) {
            self.cancelBlock();


...ie `cancelBlock` calls `cancel` which calls `cancelBlock`...

Probably is a I can't recreate this error so I'm trying to come at it by following the code logic...

**Comment by timkoma** [comment]
You can try my PR: https://github.com/rs/SDWebImage/pull/1069

**Comment by bpoplauschi** [comment]
Let's see if this still happens with 4.0. It shouldn't
