### ISSUE TITLE
[Discussion] Migration to NSURLSessions

### ISSUE THREAD

**Issue by rromanchuk** [rs/SDWebImage#823]
With ios8 supporting SPDY out of the box for `NSURLSessions`, any thoughts on migrating away from `NSURLConnection` and moving to `NSURLSessions` which now have support (since beta 2) for priorities, background transfer service, and SPDY (for free). 

This is essentially an entire rewrite of SDWebImage, so more of a pipe dream, but i'm curious of what everyone's thoughts are

**Comment by plivesey** [comment]
I'm looking for a feature to make fetching from the network even more generic. We would like to integrate SDWebImage with our own network stack. One of the reasons for doing this is NSURLSession, but we have other reasons (such as having a single point to test network diagnostics).

There are a couple of ways of doing this, but possibly the easiest way of doing it is to make SDWebImageDownloaderOperation subclassable. It isn't really right now because so much of the logic occurs in the NSURLConnection delegates.

I'd be willing to do the work to make this change (mostly just refactoring the methods which do the actual work into different methods and adding documentation), but wanted to see if it was something people were interested in.

Also, should I add a new issue for this discussion?

**Comment by rromanchuk** [comment]
It's basically an entire rewrite :stuck_out_tongue_winking_eye:   Look how https://github.com/path/FastImageCache completely separated networking from caching.

**Comment by plivesey** [comment]
So, taking another look at SDWebImage stuff, it looks like this functionality is sort of there. You can specify the operation class which seems to be a good hook into the networking:

From the docs:
* Sets a subclass of `SDWebImageDownloaderOperation` as the default
 * `NSOperation` to be used each time SDWebImage constructs a request
 * operation to download an image.

However, SDWebImageDownloaderOperation isn't easily subclassable right now. If it had some methods in the .h like downloadImageWithURL, and processData:(NSData *) etc, then this would be a workable solution (maybe not as good as FastImageCache though).

**Comment by bpoplauschi** [comment]
@plivesey @rromanchuk one idea would be to properly separate the layers in our code (as FastImageCache does) and adopt AFNetworking for the actual network part. That way we can benefit from their support for both `NSURLConnection` and `NSURLSession`, all the up-to-date code and fixes.

**Comment by kean** [comment]
You may want to check out [DFImageManager](https://github.com/kean/DFImageManager), it does exactly that. There is a simple built-in networking based on NSURLSession. And there is a DFImageManager/AFNetworking subspec that replaces networking stack with AFNetworking. If also features`FLAnimatedImage` integration and much more.

**Comment by bpoplauschi** [comment]
Resolved by #1578

**Comment by bpoplauschi** [comment]
3.8.0 version was just released.
